/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-8-30: 13h:50m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_2 ;

typedef struct {
int tag ;
ats_uint_type atslab_0 ;
} anairiats_sum_3 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_4 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_uint_type atslab_1 ;
} anairiats_sum_5 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__CK_case_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__CK_case_pos_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__CK_case_neg_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2EFFset_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2EFFexp_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2EFFadd_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__T3E_effenv_check_set_74) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__T3E_effenv_check_sexp_75) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFFENVITMeff_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFFENVITMeffmask_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFILSTcons_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFILSTmark_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFILSTnil_2) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_print_newline) () ;
ATSextern_fun(ats_void_type, atspre_prerr_newline) () ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_print_string) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_prerr_string) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, patsopt_prerrf_ifdebug) (ats_ptr_type, ...) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__prerr_location) (ats_ptr_type) ;
ATSextern_val(ats_uint_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_nil) ;
ATSextern_val(ats_uint_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_ntm) ;
ATSextern_val(ats_uint_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_exn) ;
ATSextern_val(ats_uint_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_ref) ;
ATSextern_val(ats_uint_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_wrt) ;
ATSextern_fun(ats_uint_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_sing) (ats_int_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_isnil) (ats_uint_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_supset) (ats_uint_type, ats_uint_type) ;
ATSextern_fun(ats_uint_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_diff) (ats_uint_type, ats_uint_type) ;
ATSextern_fun(ats_uint_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_inter) (ats_uint_type, ats_uint_type) ;
ATSextern_fun(ats_uint_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_union) (ats_uint_type, ats_uint_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__prerr_effset) (ats_uint_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__print_s2exp) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__prerr_s2exp) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2eff_contain_exp) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp2hnf) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2hnf2exp) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2eff_hnfize) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__the_trans3errlst_add) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_pop) () ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_set) (ats_uint_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_set) (ats_ptr_type, ats_uint_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_exn) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_sexp) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_s2eff) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_uint_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_diff_s2eff) (ats_uint_type, ats_ptr_type) ;
ATSextern_fun(ats_uint_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_union_s2eff) (ats_uint_type, ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2basics_dyn_2esats__unit_v_elim_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__sasp__effenv_push_v = 0 ;

/* sum constructor declarations */
ATSglobal(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFFENVITMeff_0) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFFENVITMeffmask_1) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFILSTcons_0) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFILSTmark_1) ;
ATSglobal(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFILSTnil_2) ;

/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_void_type prerr_FILENAME_02047_ () ;
static
ats_ptr_type efilst_mark_1 (ats_ptr_type arg0) ;
static
ats_ptr_type efilst_unmark_2 (ats_ptr_type arg0) ;
static
ats_ptr_type ref_01088_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_void_type prerr_error3_loc_02053_ (ats_ptr_type arg0) ;
static
ats_void_type auxerr_15 (ats_ptr_type env0, ats_uint_type env1, ats_uint_type arg0) ;
static
ats_clo_ptr_type auxerr_15_closure_make (ats_ptr_type env0, ats_uint_type env1) ;
static
ats_void_type auxerr_15_clofun (ats_clo_ptr_type cloptr, ats_uint_type arg0) ;
static
ats_int_type auxcheck_17 (ats_ptr_type env0, ats_uint_type env1, ats_ptr_type arg0, ats_uint_type arg1) ;
static
ats_clo_ptr_type auxcheck_17_closure_make (ats_ptr_type env0, ats_uint_type env1) ;
static
ats_int_type auxcheck_17_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0, ats_uint_type arg1) ;
static
ats_void_type auxerr_25 (ats_ptr_type env0, ats_ptr_type arg0) ;
static
ats_clo_ptr_type auxerr_25_closure_make (ats_ptr_type env0) ;
static
ats_void_type auxerr_25_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_int_type auxcheck_26 (ats_ptr_type env0, ats_ptr_type arg0, ats_uint_type arg1, ats_ptr_type arg2) ;
static
ats_clo_ptr_type auxcheck_26_closure_make (ats_ptr_type env0) ;
static
ats_int_type auxcheck_26_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0, ats_uint_type arg1, ats_ptr_type arg2) ;

/* partial value template declarations */
/* static temporary variable declarations */
ATSstatic (ats_ptr_type, statmp15) ;
ATSstatic (ats_ptr_type, statmp18) ;

/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 1606(line=47, offs=28) -- 1641(line=47, offs=63)
*/
ATSstaticdec()
ats_void_type
prerr_FILENAME_02047_ () {
/* local vardec */
// ATSlocal_void (tmp0) ;

__ats_lab_prerr_FILENAME_02047_:
/* tmp0 = */ atspre_prerr_string (ATSstrcst("pats_trans3_env_effect")) ;
return /* (tmp0) */ ;
} /* end of [prerr_FILENAME_02047_] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 2264(line=80, offs=1) -- 2350(line=82, offs=54)
*/
ATSstaticdec()
ats_ptr_type
efilst_mark_1 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp1) ;

__ats_lab_efilst_mark_1:
tmp1 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)tmp1)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_1, tmp1, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_1, tmp1, atslab_1, arg0) ;
return (tmp1) ;
} /* end of [efilst_mark_1] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 2380(line=86, offs=1) -- 2578(line=93, offs=34)
*/
ATSstaticdec()
ats_ptr_type
efilst_unmark_2 (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;
ATSlocal (ats_ptr_type, tmp4) ;

__ats_lab_efilst_unmark_2:
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp3 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_1) ;
ATS_FREE(arg0) ;
arg0 = tmp3 ;
goto __ats_lab_efilst_unmark_2 ; // tail call
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp4 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
ATS_FREE(arg0) ;
tmp2 = tmp4 ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
// if (((ats_sum_ptr_type)arg0)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_2_1:
tmp2 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFILSTnil_2) ;
break ;
} while (0) ;
return (tmp2) ;
} /* end of [efilst_unmark_2] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 2724(line=103, offs=3) -- 2963(line=109, offs=6)
*/
ATSglobaldec()
ats_uint_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_diff_s2eff (ats_uint_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_uint_type, tmp5) ;
ATSlocal (ats_uint_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_uint_type, tmp9) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_diff_s2eff:
do {
/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)arg1)->tag != 0) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp6 = ats_caselptrlab_mac(anairiats_sum_3, arg1, atslab_0) ;
tmp5 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_diff (arg0, tmp6) ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)arg1)->tag != 1) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp5 = arg0 ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
// if (((ats_sum_ptr_type)arg1)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_5_1:
tmp7 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
tmp8 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_1) ;
tmp9 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_diff_s2eff (arg0, tmp7) ;
arg0 = tmp9 ;
arg1 = tmp8 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_diff_s2eff ; // tail call
break ;
} while (0) ;
return (tmp5) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_diff_s2eff] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 3117(line=117, offs=3) -- 3359(line=123, offs=6)
*/
ATSglobaldec()
ats_uint_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_union_s2eff (ats_uint_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_uint_type, tmp10) ;
ATSlocal (ats_uint_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_uint_type, tmp14) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_union_s2eff:
do {
/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)arg1)->tag != 0) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp11 = ats_caselptrlab_mac(anairiats_sum_3, arg1, atslab_0) ;
tmp10 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_union (arg0, tmp11) ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)arg1)->tag != 1) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp10 = arg0 ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
// if (((ats_sum_ptr_type)arg1)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_8_1:
tmp12 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_0) ;
tmp13 = ats_caselptrlab_mac(anairiats_sum_2, arg1, atslab_1) ;
tmp14 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_union_s2eff (arg0, tmp12) ;
arg0 = tmp14 ;
arg1 = tmp13 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_union_s2eff ; // tail call
break ;
} while (0) ;
return (tmp10) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_union_s2eff] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/reference.dats: 1828(line=57, offs=18) -- 1902(line=59, offs=4)
*/
ATSstaticdec()
ats_ptr_type
ref_01088_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;

__ats_lab_ref_01088_ats_ptr_type:
/* ats_ptr_type tmp17 ; */
tmp17 = arg0 ;
tmp16 = atspre_ref_make_elt_tsz ((&tmp17), sizeof(ats_ptr_type)) ;
return (tmp16) ;
} /* end of [ref_01088_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 3595(line=139, offs=3) -- 3753(line=145, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_add_eff (ats_int_type arg0) {
/* local vardec */
// ATSlocal_void (tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_uint_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_add_eff:
tmp20 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp15), atslab_1) ;
tmp21 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_sing (arg0) ;
tmp22 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp22)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_3, tmp22, atslab_0, tmp21) ;
tmp24 = ats_ptrget_mac(ats_ptr_type, tmp20) ;
tmp23 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp23)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_2, tmp23, atslab_0, tmp22) ;
ats_selptrset_mac(anairiats_sum_2, tmp23, atslab_1, tmp24) ;
ats_ptrget_mac(ats_ptr_type, tmp20) = tmp23 ;
return /* (tmp19) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_add_eff] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 3834(line=151, offs=3) -- 3969(line=156, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_pop () {
/* local vardec */
// ATSlocal_void (tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;
ATSlocal (ats_ptr_type, tmp28) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_pop:
tmp26 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp15), atslab_1) ;
tmp28 = ats_ptrget_mac(ats_ptr_type, tmp26) ;
tmp27 = efilst_unmark_2 (tmp28) ;
ats_ptrget_mac(ats_ptr_type, tmp26) = tmp27 ;
return /* (tmp25) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_pop] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 4028(line=160, offs=3) -- 4188(line=166, offs=6)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_pop_if (ats_bool_type arg0) {
/* local vardec */
// ATSlocal_void (tmp29) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_pop_if:
if (arg0) {
/* tmp29 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_pop () ;
} else {
/* empty */
} /* end of [if] */
return /* (tmp29) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_pop_if] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 4282(line=172, offs=17) -- 4432(line=179, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push () {
/* local vardec */
// ATSlocal_void (tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push:
tmp31 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp15), atslab_1) ;
tmp33 = ats_ptrget_mac(ats_ptr_type, tmp31) ;
tmp32 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)tmp32)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_1, tmp32, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_1, tmp32, atslab_1, tmp33) ;
ats_ptrget_mac(ats_ptr_type, tmp31) = tmp32 ;
return /* (tmp30) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 4494(line=183, offs=3) -- 4696(line=192, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_lam (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_lam:
tmp35 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp35)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_4, tmp35, atslab_0, arg0) ;
tmp36 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp15), atslab_1) ;
tmp38 = ats_ptrget_mac(ats_ptr_type, tmp36) ;
tmp37 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)tmp37)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_1, tmp37, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_1, tmp37, atslab_1, tmp38) ;
tmp39 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp39)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_2, tmp39, atslab_0, tmp35) ;
ats_selptrset_mac(anairiats_sum_2, tmp39, atslab_1, tmp37) ;
ats_ptrget_mac(ats_ptr_type, tmp36) = tmp39 ;
return /* (tmp34) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_lam] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 4781(line=197, offs=21) -- 4977(line=206, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_set (ats_uint_type arg0) {
/* local vardec */
// ATSlocal_void (tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_set:
tmp41 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp41)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_3, tmp41, atslab_0, arg0) ;
tmp42 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp15), atslab_1) ;
tmp44 = ats_ptrget_mac(ats_ptr_type, tmp42) ;
tmp43 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)tmp43)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_1, tmp43, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_1, tmp43, atslab_1, tmp44) ;
tmp45 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp45)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_2, tmp45, atslab_0, tmp41) ;
ats_selptrset_mac(anairiats_sum_2, tmp45, atslab_1, tmp43) ;
ats_ptrget_mac(ats_ptr_type, tmp42) = tmp45 ;
return /* (tmp40) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_set] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 5046(line=210, offs=3) -- 5202(line=215, offs=28)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_set_if (ats_bool_type arg0, ats_uint_type arg1) {
/* local vardec */
// ATSlocal_void (tmp46) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_set_if:
if (arg0) {
/* tmp46 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_set (arg1) ;
} else {
/* empty */
} /* end of [if] */
return /* (tmp46) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_set_if] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 5296(line=221, offs=25) -- 5498(line=230, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_effmask (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;
ATSlocal (ats_ptr_type, tmp52) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_effmask:
tmp48 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp48)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_4, tmp48, atslab_0, arg0) ;
tmp49 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp15), atslab_1) ;
tmp51 = ats_ptrget_mac(ats_ptr_type, tmp49) ;
tmp50 = ATS_MALLOC(sizeof(anairiats_sum_1)) ;
((ats_sum_ptr_type)tmp50)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_1, tmp50, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_1, tmp50, atslab_1, tmp51) ;
tmp52 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp52)->tag = 0 ;
ats_selptrset_mac(anairiats_sum_2, tmp52, atslab_0, tmp48) ;
ats_selptrset_mac(anairiats_sum_2, tmp52, atslab_1, tmp50) ;
ats_ptrget_mac(ats_ptr_type, tmp49) = tmp52 ;
return /* (tmp47) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_push_effmask] */

/*
// /home/hwxi/research/Postiats/git/src/pats_errmsg.dats: 2164(line=76, offs=18) -- 2223(line=79, offs=2)
*/
ATSstaticdec()
ats_void_type
prerr_error3_loc_02053_ (ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp56) ;
// ATSlocal_void (tmp57) ;

__ats_lab_prerr_error3_loc_02053_:
/* tmp57 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_location_2esats__prerr_location (arg0) ;
/* tmp56 = */ atspre_prerr_string (ATSstrcst(": error(3)")) ;
return /* (tmp56) */ ;
} /* end of [prerr_error3_loc_02053_] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 5733(line=242, offs=5) -- 6052(line=252, offs=4)
*/
ATSstaticdec()
ats_void_type
auxerr_15 (ats_ptr_type env0, ats_uint_type env1, ats_uint_type arg0) {
/* local vardec */
// ATSlocal_void (tmp54) ;
// ATSlocal_void (tmp55) ;
// ATSlocal_void (tmp58) ;
// ATSlocal_void (tmp59) ;
// ATSlocal_void (tmp60) ;
// ATSlocal_void (tmp61) ;
ATSlocal (ats_ptr_type, tmp62) ;

__ats_lab_auxerr_15:
/* tmp55 = */ prerr_error3_loc_02053_ (env0) ;
/* tmp58 = */ patsopt_prerrf_ifdebug (ATSstrcst(": [%s]: %s"), ATSstrcst("/home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats"), ATSstrcst("the_effenv_check_set")) ;
/* tmp59 = */ atspre_prerr_string (ATSstrcst(": some disallowed effects may be incurred: ")) ;
/* tmp60 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__prerr_effset (arg0) ;
/* tmp61 = */ atspre_prerr_newline () ;
tmp62 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
((ats_sum_ptr_type)tmp62)->tag = 74 ;
ats_selptrset_mac(anairiats_sum_5, tmp62, atslab_0, env0) ;
ats_selptrset_mac(anairiats_sum_5, tmp62, atslab_1, env1) ;
/* tmp54 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__the_trans3errlst_add (tmp62) ;
return /* (tmp54) */ ;
} /* end of [auxerr_15] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
ats_uint_type closure_env_1 ;
} auxerr_15_closure_type ;

ats_void_type
auxerr_15_clofun (ats_clo_ptr_type cloptr, ats_uint_type arg0) {
auxerr_15 (((auxerr_15_closure_type*)cloptr)->closure_env_0, ((auxerr_15_closure_type*)cloptr)->closure_env_1, arg0) ; return ;
} /* end of function */

ATSinline()
ats_void_type
auxerr_15_closure_init (auxerr_15_closure_type *p_clo, ats_ptr_type env0, ats_uint_type env1) {
p_clo->closure_fun = (ats_fun_ptr_type)&auxerr_15_clofun ;
p_clo->closure_env_0 = env0 ;
p_clo->closure_env_1 = env1 ;
return ;
} /* end of function */

ats_clo_ptr_type
auxerr_15_closure_make (ats_ptr_type env0, ats_uint_type env1) {
auxerr_15_closure_type *p_clo = ATS_MALLOC(sizeof(auxerr_15_closure_type)) ;
auxerr_15_closure_init (p_clo, env0, env1) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 6084(line=254, offs=5) -- 7400(line=295, offs=38)
*/
ATSstaticdec()
ats_int_type
auxcheck_17 (ats_ptr_type env0, ats_uint_type env1, ats_ptr_type arg0, ats_uint_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp63) ;
ATSlocal (ats_ptr_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_uint_type, tmp66) ;
ATSlocal (ats_uint_type, tmp67) ;
ATSlocal (ats_bool_type, tmp68) ;
ATSlocal (ats_int_type, tmp69) ;
ATSlocal (ats_ptr_type, tmp70) ;
// ATSlocal_void (tmp71) ;
ATSlocal (ats_bool_type, tmp72) ;
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (ats_uint_type, tmp74) ;
ATSlocal (ats_bool_type, tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_int_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;
ATSlocal (ats_int_type, tmp79) ;
ATSlocal (ats_bool_type, tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;
// ATSlocal_void (tmp82) ;
ATSlocal (ats_bool_type, tmp83) ;
ATSlocal (ats_bool_type, tmp84) ;

__ats_lab_auxcheck_17:
do {
/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_12_0 ; }
__ats_lab_9_1:
tmp64 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp65 = &ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_1) ;
do {
/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (((ats_sum_ptr_type)tmp64)->tag != 0) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp66 = ats_caselptrlab_mac(anairiats_sum_3, tmp64, atslab_0) ;
tmp67 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_inter (arg1, tmp66) ;
tmp68 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_isnil (tmp67) ;
if (tmp68) {
tmp70 = ats_ptrget_mac(ats_ptr_type, tmp65) ;
tmp69 = auxcheck_17 (env0, env1, tmp70, arg1) ;
} else {
tmp69 = 1 ;
} /* end of [if] */
tmp72 = atspre_gt_int_int (tmp69, 0) ;
if (tmp72) {
/* tmp71 = */ auxerr_15 (env0, env1, tmp67) ;
} else {
/* empty */
} /* end of [if] */
tmp63 = tmp69 ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
// if (((ats_sum_ptr_type)tmp64)->tag != 1) { ats_deadcode_failure_handle () ; }
__ats_lab_11_1:
tmp73 = ats_caselptrlab_mac(anairiats_sum_4, tmp64, atslab_0) ;
tmp74 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_diff_s2eff (arg1, tmp73) ;
tmp75 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_isnil (tmp74) ;
if (tmp75) {
tmp63 = 0 ;
} else {
tmp76 = ats_ptrget_mac(ats_ptr_type, tmp65) ;
arg0 = tmp76 ;
arg1 = tmp74 ;
goto __ats_lab_auxcheck_17 ; // tail call
} /* end of [if] */
break ;
} while (0) ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
tmp77 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp78 = &ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
tmp80 = atspre_gt_int_int (tmp77, 0) ;
if (tmp80) {
tmp79 = 1 ;
} else {
tmp81 = ats_ptrget_mac(ats_ptr_type, tmp78) ;
tmp79 = auxcheck_17 (env0, env1, tmp81, arg1) ;
} /* end of [if] */
tmp83 = atspre_gt_int_int (tmp77, 0) ;
if (tmp83) {
tmp84 = atspre_gt_int_int (tmp79, 0) ;
if (tmp84) {
/* tmp82 = */ auxerr_15 (env0, env1, arg1) ;
} else {
/* empty */
} /* end of [if] */
} else {
/* empty */
} /* end of [if] */
tmp63 = tmp79 ;
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
// if (((ats_sum_ptr_type)arg0)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_13_1:
tmp63 = 0 ;
break ;
} while (0) ;
return (tmp63) ;
} /* end of [auxcheck_17] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
ats_uint_type closure_env_1 ;
} auxcheck_17_closure_type ;

ats_int_type
auxcheck_17_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0, ats_uint_type arg1) {
return auxcheck_17 (((auxcheck_17_closure_type*)cloptr)->closure_env_0, ((auxcheck_17_closure_type*)cloptr)->closure_env_1, arg0, arg1) ;
} /* end of function */

ATSinline()
ats_void_type
auxcheck_17_closure_init (auxcheck_17_closure_type *p_clo, ats_ptr_type env0, ats_uint_type env1) {
p_clo->closure_fun = (ats_fun_ptr_type)&auxcheck_17_clofun ;
p_clo->closure_env_0 = env0 ;
p_clo->closure_env_1 = env1 ;
return ;
} /* end of function */

ats_clo_ptr_type
auxcheck_17_closure_make (ats_ptr_type env0, ats_uint_type env1) {
auxcheck_17_closure_type *p_clo = ATS_MALLOC(sizeof(auxcheck_17_closure_type)) ;
auxcheck_17_closure_init (p_clo, env0, env1) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 5590(line=236, offs=3) -- 7601(line=308, offs=4)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_set (ats_ptr_type arg0, ats_uint_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp53) ;
ATSlocal (ats_bool_type, tmp85) ;
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_set:
tmp85 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_isnil (arg1) ;
if (tmp85) {
tmp53 = 0 ;
} else {
tmp86 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp15), atslab_1) ;
tmp87 = ats_ptrget_mac(ats_ptr_type, tmp86) ;
tmp53 = auxcheck_17 (arg0, arg1, tmp87, arg1) ;
} /* end of [if] */
return (tmp53) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_set] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 7690(line=314, offs=3) -- 7754(line=315, offs=49)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_eff (ats_ptr_type arg0, ats_int_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp88) ;
ATSlocal (ats_uint_type, tmp89) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_eff:
tmp89 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_sing (arg1) ;
tmp88 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_set (arg0, tmp89) ;
return (tmp88) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_eff] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 7824(line=320, offs=3) -- 7872(line=320, offs=51)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_exn (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp90) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_exn:
tmp90 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_set (arg0, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_exn) ;
return (tmp90) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_exn] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 7940(line=325, offs=3) -- 7988(line=325, offs=51)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_ntm (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp91) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_ntm:
tmp91 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_set (arg0, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_ntm) ;
return (tmp91) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_ntm] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 8056(line=330, offs=3) -- 8104(line=330, offs=51)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_ref (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp92) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_ref:
tmp92 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_set (arg0, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_ref) ;
return (tmp92) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_ref] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 8172(line=335, offs=3) -- 8220(line=335, offs=51)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_wrt (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp93) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_wrt:
tmp93 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_set (arg0, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_wrt) ;
return (tmp93) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_wrt] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 8317(line=342, offs=3) -- 8482(line=345, offs=24)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_caskind_check_exn (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp94) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_caskind_check_exn:
do {
/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (((ats_sum_ptr_type)arg1)->tag != 0) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
tmp94 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_exn (arg0) ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (((ats_sum_ptr_type)arg1)->tag != 1) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
tmp94 = 0 ;
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
// if (((ats_sum_ptr_type)arg1)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_16_1:
tmp94 = 0 ;
break ;
} while (0) ;
return (tmp94) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_caskind_check_exn] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 8769(line=358, offs=5) -- 9090(line=368, offs=4)
*/
ATSstaticdec()
ats_void_type
auxerr_25 (ats_ptr_type env0, ats_ptr_type arg0) {
/* local vardec */
// ATSlocal_void (tmp99) ;
// ATSlocal_void (tmp100) ;
// ATSlocal_void (tmp101) ;
// ATSlocal_void (tmp102) ;
// ATSlocal_void (tmp103) ;
// ATSlocal_void (tmp104) ;
ATSlocal (ats_ptr_type, tmp105) ;

__ats_lab_auxerr_25:
/* tmp100 = */ prerr_error3_loc_02053_ (env0) ;
/* tmp101 = */ patsopt_prerrf_ifdebug (ATSstrcst(": [%s]: %s"), ATSstrcst("/home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats"), ATSstrcst("the_effenv_check_sexp")) ;
/* tmp102 = */ atspre_prerr_string (ATSstrcst(": some disallowed effects may be incurred: ")) ;
/* tmp103 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__prerr_s2exp (arg0) ;
/* tmp104 = */ atspre_prerr_newline () ;
tmp105 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
((ats_sum_ptr_type)tmp105)->tag = 75 ;
ats_selptrset_mac(anairiats_sum_2, tmp105, atslab_0, env0) ;
ats_selptrset_mac(anairiats_sum_2, tmp105, atslab_1, arg0) ;
/* tmp99 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__the_trans3errlst_add (tmp105) ;
return /* (tmp99) */ ;
} /* end of [auxerr_25] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} auxerr_25_closure_type ;

ats_void_type
auxerr_25_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
auxerr_25 (((auxerr_25_closure_type*)cloptr)->closure_env_0, arg0) ; return ;
} /* end of function */

ATSinline()
ats_void_type
auxerr_25_closure_init (auxerr_25_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&auxerr_25_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
auxerr_25_closure_make (ats_ptr_type env0) {
auxerr_25_closure_type *p_clo = ATS_MALLOC(sizeof(auxerr_25_closure_type)) ;
auxerr_25_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 9120(line=370, offs=5) -- 10309(line=404, offs=46)
*/
ATSstaticdec()
ats_int_type
auxcheck_26 (ats_ptr_type env0, ats_ptr_type arg0, ats_uint_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_int_type, tmp106) ;
ATSlocal (ats_ptr_type, tmp107) ;
ATSlocal (ats_ptr_type, tmp108) ;
ATSlocal (ats_uint_type, tmp109) ;
ATSlocal (ats_bool_type, tmp110) ;
ATSlocal (ats_int_type, tmp111) ;
// ATSlocal_void (tmp112) ;
ATSlocal (ats_bool_type, tmp113) ;
ATSlocal (ats_ptr_type, tmp114) ;
ATSlocal (ats_bool_type, tmp115) ;
ATSlocal (ats_uint_type, tmp116) ;
ATSlocal (ats_ptr_type, tmp117) ;
ATSlocal (ats_int_type, tmp118) ;
ATSlocal (ats_ptr_type, tmp119) ;
ATSlocal (ats_int_type, tmp120) ;
ATSlocal (ats_bool_type, tmp121) ;
ATSlocal (ats_ptr_type, tmp122) ;
// ATSlocal_void (tmp123) ;
ATSlocal (ats_bool_type, tmp124) ;

__ats_lab_auxcheck_26:
do {
/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_20_0 ; }
__ats_lab_17_1:
tmp107 = ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_0) ;
tmp108 = &ats_caselptrlab_mac(anairiats_sum_2, arg0, atslab_1) ;
do {
/* branch: __ats_lab_18 */
__ats_lab_18_0:
if (((ats_sum_ptr_type)tmp107)->tag != 0) { goto __ats_lab_19_0 ; }
__ats_lab_18_1:
tmp109 = ats_caselptrlab_mac(anairiats_sum_3, tmp107, atslab_0) ;
tmp110 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_supset (arg1, tmp109) ;
if (tmp110) {
tmp111 = 0 ;
} else {
tmp111 = 1 ;
} /* end of [if] */
tmp113 = atspre_gt_int_int (tmp111, 0) ;
if (tmp113) {
/* tmp112 = */ auxerr_25 (env0, arg2) ;
} else {
/* empty */
} /* end of [if] */
tmp106 = tmp111 ;
break ;

/* branch: __ats_lab_19 */
__ats_lab_19_0:
// if (((ats_sum_ptr_type)tmp107)->tag != 1) { ats_deadcode_failure_handle () ; }
__ats_lab_19_1:
tmp114 = ats_caselptrlab_mac(anairiats_sum_4, tmp107, atslab_0) ;
tmp115 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2eff_contain_exp (tmp114, arg2) ;
if (tmp115) {
tmp106 = 0 ;
} else {
tmp116 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__effset_union_s2eff (arg1, tmp114) ;
tmp117 = ats_ptrget_mac(ats_ptr_type, tmp108) ;
arg0 = tmp117 ;
arg1 = tmp116 ;
arg2 = arg2 ;
goto __ats_lab_auxcheck_26 ; // tail call
} /* end of [if] */
break ;
} while (0) ;
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
if (((ats_sum_ptr_type)arg0)->tag != 1) { goto __ats_lab_21_0 ; }
__ats_lab_20_1:
tmp118 = ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_0) ;
tmp119 = &ats_caselptrlab_mac(anairiats_sum_1, arg0, atslab_1) ;
tmp121 = atspre_gt_int_int (tmp118, 0) ;
if (tmp121) {
tmp120 = 1 ;
} else {
tmp122 = ats_ptrget_mac(ats_ptr_type, tmp119) ;
tmp120 = auxcheck_26 (env0, tmp122, arg1, arg2) ;
} /* end of [if] */
tmp124 = atspre_gt_int_int (tmp120, 0) ;
if (tmp124) {
/* tmp123 = */ auxerr_25 (env0, arg2) ;
} else {
/* empty */
} /* end of [if] */
tmp106 = tmp120 ;
break ;

/* branch: __ats_lab_21 */
__ats_lab_21_0:
// if (((ats_sum_ptr_type)arg0)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_21_1:
tmp106 = 0 ;
break ;
} while (0) ;
return (tmp106) ;
} /* end of [auxcheck_26] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} auxcheck_26_closure_type ;

ats_int_type
auxcheck_26_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0, ats_uint_type arg1, ats_ptr_type arg2) {
return auxcheck_26 (((auxcheck_26_closure_type*)cloptr)->closure_env_0, arg0, arg1, arg2) ;
} /* end of function */

ATSinline()
ats_void_type
auxcheck_26_closure_init (auxcheck_26_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&auxcheck_26_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
auxcheck_26_closure_make (ats_ptr_type env0) {
auxcheck_26_closure_type *p_clo = ATS_MALLOC(sizeof(auxcheck_26_closure_type)) ;
auxcheck_26_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 8620(line=352, offs=3) -- 10435(line=411, offs=4)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_sexp (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp95) ;
// ATSlocal_void (tmp96) ;
// ATSlocal_void (tmp97) ;
// ATSlocal_void (tmp98) ;
ATSlocal (ats_ptr_type, tmp125) ;
ATSlocal (ats_ptr_type, tmp126) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_sexp:
/* tmp96 = */ atspre_print_string (ATSstrcst("the_effenv_check_sexp: s2e0 = ")) ;
/* tmp97 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__print_s2exp (arg1) ;
/* tmp98 = */ atspre_print_newline () ;
tmp125 = ats_selsin_mac(ats_castfn_mac(ats_ptr_type, statmp15), atslab_1) ;
tmp126 = ats_ptrget_mac(ats_ptr_type, tmp125) ;
tmp95 = auxcheck_26 (arg0, tmp126, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__effset_nil, arg1) ;
return (tmp95) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_sexp] */

/*
// /home/hwxi/research/Postiats/git/src/pats_trans3_env_effect.dats: 10527(line=417, offs=3) -- 11126(line=442, offs=4)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_s2eff (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp127) ;
ATSlocal (ats_ptr_type, tmp128) ;
ATSlocal (ats_uint_type, tmp129) ;
ATSlocal (ats_ptr_type, tmp130) ;
ATSlocal (ats_ptr_type, tmp131) ;
ATSlocal (ats_ptr_type, tmp132) ;
ATSlocal (ats_ptr_type, tmp133) ;
ATSlocal (ats_ptr_type, tmp134) ;
ATSlocal (ats_int_type, tmp135) ;
ATSlocal (ats_bool_type, tmp136) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_s2eff:
tmp128 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2eff_hnfize (arg1) ;
do {
/* branch: __ats_lab_22 */
__ats_lab_22_0:
if (((ats_sum_ptr_type)tmp128)->tag != 0) { goto __ats_lab_23_0 ; }
__ats_lab_22_1:
tmp129 = ats_caselptrlab_mac(anairiats_sum_3, tmp128, atslab_0) ;
tmp127 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_set (arg0, tmp129) ;
break ;

/* branch: __ats_lab_23 */
__ats_lab_23_0:
if (((ats_sum_ptr_type)tmp128)->tag != 1) { goto __ats_lab_24_0 ; }
__ats_lab_23_1:
tmp130 = ats_caselptrlab_mac(anairiats_sum_4, tmp128, atslab_0) ;
tmp131 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp2hnf (tmp130) ;
tmp132 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2hnf2exp (tmp131) ;
tmp127 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_sexp (arg0, tmp132) ;
break ;

/* branch: __ats_lab_24 */
__ats_lab_24_0:
// if (((ats_sum_ptr_type)tmp128)->tag != 2) { ats_deadcode_failure_handle () ; }
__ats_lab_24_1:
tmp133 = ats_caselptrlab_mac(anairiats_sum_2, tmp128, atslab_0) ;
tmp134 = ats_caselptrlab_mac(anairiats_sum_2, tmp128, atslab_1) ;
tmp135 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_s2eff (arg0, tmp133) ;
tmp136 = atspre_gt_int_int (tmp135, 0) ;
if (tmp136) {
tmp127 = 1 ;
} else {
arg0 = arg0 ;
arg1 = tmp134 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_s2eff ; // tail call
} /* end of [if] */
break ;
} while (0) ;
return (tmp127) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__the_effenv_check_s2eff] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_errmsg_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_errmsg_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_errmsg_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_errmsg_2edats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_effect_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_2esats__staload () ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFFENVITMeff_0.tag = 0 ;
// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFFENVITMeffmask_1.tag = 1 ;
// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFILSTcons_0.tag = 0 ;
// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFILSTmark_1.tag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFILSTnil_2.tag = 2 ;
return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e10_2prelude_2basics_dyn_2esats__unit_v_elim_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */
ATS_GC_MARKROOT(&statmp15, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp18, sizeof(ats_ptr_type)) ;

/* marking external values for GC */

/* code for dynamic loading */
statmp18 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_trans3_env_effect_2edats__EFILSTnil_2) ;
statmp15 = ref_01088_ats_ptr_type (statmp18) ;
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_trans3_env_effect_dats.c] */
