/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-9-2: 21h:28m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef
struct {
ats_ptr_type atslab_primval_loc ;
ats_ptr_type atslab_primval_type ;
ats_ptr_type atslab_primval_node ;
} anairiats_rec_1 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_2 ;

typedef struct {
ats_int_type atslab_0 ;
} anairiats_sum_3 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_4 ;

typedef
struct {
ats_ptr_type atslab_instr_loc ;
ats_ptr_type atslab_instr_node ;
} anairiats_rec_5 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
} anairiats_sum_6 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_int_type atslab_2 ;
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_sum_7 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_8 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
ats_ptr_type atslab_5 ;
ats_ptr_type atslab_6 ;
ats_ptr_type atslab_7 ;
} anairiats_sum_9 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_10 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_11 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_sum_12 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
} anairiats_sum_13 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_int_type atslab_2 ;
} anairiats_sum_14 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_15 ;

typedef
struct {
ats_ptr_type atslab_ibranch_loc ;
ats_ptr_type atslab_ibranch_inslst ;
} anairiats_rec_16 ;

typedef
struct {
ats_ptr_type atslab_primdec_loc ;
ats_ptr_type atslab_primdec_node ;
} anairiats_rec_17 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FUNCLOfun_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FUNCLOclo_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__TMPSUBcons_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__TMPSUBnil_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMVtmpref_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMVargref_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMVtop_18) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMVcastfn_21) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMVselcon_22) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMVselect_23) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMVselect2_24) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMVselptr_25) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMVlamfix_32) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDnone_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDlist_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDsaspdec_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDdatdecs_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDexndecs_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDfundecs_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDvaldecs_6) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDvaldecs_rec_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDvardecs_8) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDimpdec_9) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDinclude_10) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDstaload_11) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDdynload_12) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PMDlocal_13) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__PTCKNTnone_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSfunlab_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INStmplab_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INScomment_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSmove_val_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSpmove_val_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSmove_arg_val_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSfcall_6) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSfcall2_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSextfcall_8) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INScond_9) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSfreecon_10) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSloop_11) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSloopexn_12) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INScaseof_13) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSletpop_14) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSletpush_15) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSmove_con_16) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSmove_ref_17) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSmove_boxrec_18) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSmove_fltrec_19) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSpatck_20) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSmove_ptrofsel_21) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSstore_ptrofs_22) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSxstore_ptrofs_23) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSraise_24) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INStrywith_25) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSmove_list_nil_26) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSpmove_list_nil_27) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSpmove_list_cons_28) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSmove_list_phead_29) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSmove_list_ptail_30) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSmove_arrpsz_ptr_31) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSstore_arrpsz_asz_32) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSstore_arrpsz_ptr_33) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSupdate_ptrinc_34) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSupdate_ptrdec_35) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INStmpdec_36) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__INSdcstdef_37) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__stasub_make_nil) () ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__stasub_add) (ats_ref_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_void) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvar_get_type) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_nil) () ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__funlab_get_type) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__funlab_get_funclo) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpsub_append) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_is_nshared) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_funlab) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_cfunlab) (ats_ptr_type, ats_ptr_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_d2vfunlab) (ats_ptr_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_void_type loop_9 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type aux_11 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type auxlst_12 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type auxibr_13 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type auxibrlst_14 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type auxpmd_15 (ats_ref_type arg0, ats_ptr_type arg1) ;
static
ats_void_type auxpmdlst_16 (ats_ref_type arg0, ats_ptr_type arg1) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 1786(line=64, offs=16) -- 1832(line=65, offs=39)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvar_is_void (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp0) ;
ATSlocal (ats_ptr_type, tmp1) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvar_is_void:
tmp1 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvar_get_type (arg0) ;
tmp0 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_void (tmp1) ;
return (tmp0) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvar_is_void] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 1912(line=72, offs=3) -- 1952(line=72, offs=43)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_is_void (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_is_void:
tmp3 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_primval_type) ;
tmp2 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_void (tmp3) ;
return (tmp2) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_is_void] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 2029(line=78, offs=16) -- 2097(line=79, offs=59)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_is_top (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp4) ;
ATSlocal (ats_ptr_type, tmp5) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_is_top:
tmp5 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_primval_node) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)tmp5)->tag != 18) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp4 = ats_true_bool ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
__ats_lab_1_1:
tmp4 = ats_false_bool ;
break ;
} while (0) ;
return (tmp4) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_is_top] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 2312(line=90, offs=3) -- 2713(line=110, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_is_nshared (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_is_nshared:
tmp7 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_primval_node) ;
do {
/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)tmp7)->tag != 1) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp6 = ats_true_bool ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)tmp7)->tag != 3) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp6 = ats_true_bool ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)tmp7)->tag != 22) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp6 = ats_true_bool ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)tmp7)->tag != 23) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp6 = ats_true_bool ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)tmp7)->tag != 24) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp6 = ats_true_bool ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)tmp7)->tag != 25) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp6 = ats_true_bool ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)tmp7)->tag != 32) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp6 = ats_true_bool ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)tmp7)->tag != 21) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp8 = ats_caselptrlab_mac(anairiats_sum_2, tmp7, atslab_1) ;
arg0 = tmp8 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_is_nshared ; // tail call
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
__ats_lab_10_1:
tmp6 = ats_false_bool ;
break ;
} while (0) ;
return (tmp6) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_is_nshared] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 2799(line=116, offs=3) -- 3021(line=127, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_make_funlab (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;
ATSlocal (ats_ptr_type, tmp11) ;
ATSlocal (ats_int_type, tmp12) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_make_funlab:
tmp10 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__funlab_get_type (arg1) ;
tmp11 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__funlab_get_funclo (arg1) ;
do {
/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (tmp11 != (ats_sum_ptr_type)0) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp9 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_funlab (arg0, tmp10, arg1) ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
// if (tmp11 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_12_1:
tmp12 = ats_caselptrlab_mac(anairiats_sum_3, tmp11, atslab_0) ;
tmp9 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_cfunlab (arg0, tmp10, tmp12, arg1) ;
break ;
} while (0) ;
return (tmp9) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_make_funlab] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 3088(line=131, offs=3) -- 3318(line=142, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_make2_funlab (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
ATSlocal (ats_int_type, tmp16) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_make2_funlab:
tmp14 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__funlab_get_type (arg2) ;
tmp15 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__funlab_get_funclo (arg2) ;
do {
/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (tmp15 != (ats_sum_ptr_type)0) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp13 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_funlab (arg0, arg1, arg2) ;
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
// if (tmp15 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_14_1:
tmp16 = ats_caselptrlab_mac(anairiats_sum_3, tmp15, atslab_0) ;
tmp13 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_cfunlab (arg0, arg1, tmp16, arg2) ;
break ;
} while (0) ;
return (tmp13) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_make2_funlab] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 3409(line=148, offs=3) -- 3507(line=150, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_make_d2vfunlab (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_make_d2vfunlab:
tmp18 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__funlab_get_type (arg2) ;
tmp17 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_d2vfunlab (arg0, tmp18, arg1, arg2) ;
return (tmp17) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primval_make_d2vfunlab] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 3592(line=155, offs=18) -- 3651(line=156, offs=51)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__patckont_is_none (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp19) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__patckont_is_none:
do {
/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (((ats_sum_ptr_type)arg0)->tag != 0) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
tmp19 = ats_true_bool ;
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
__ats_lab_16_1:
tmp19 = ats_false_bool ;
break ;
} while (0) ;
return (tmp19) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__patckont_is_none] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 3747(line=164, offs=5) -- 3972(line=175, offs=4)
*/
ATSstaticdec()
ats_void_type
loop_9 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;
ATSlocal (ats_ptr_type, tmp24) ;
// ATSlocal_void (tmp25) ;

__ats_lab_loop_9:
do {
/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_18_0 ; }
__ats_lab_17_1:
tmp22 = ats_caselptrlab_mac(anairiats_sum_4, arg1, atslab_0) ;
tmp23 = ats_caselptrlab_mac(anairiats_sum_4, arg1, atslab_1) ;
tmp24 = ats_caselptrlab_mac(anairiats_sum_4, arg1, atslab_2) ;
/* tmp25 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__stasub_add (arg0, tmp22, tmp23) ;
arg0 = arg0 ;
arg1 = tmp24 ;
goto __ats_lab_loop_9 ; // tail call
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_18_1:
break ;
} while (0) ;
return /* (tmp21) */ ;
} /* end of [loop_9] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 3727(line=162, offs=15) -- 4074(line=183, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpsub2stasub (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp26) ;
// ATSlocal_void (tmp27) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpsub2stasub:
/* ats_ptr_type tmp26 ; */
tmp26 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__stasub_make_nil () ;
/* tmp27 = */ loop_9 ((&tmp26), arg0) ;
tmp20 = tmp26 ;
return (tmp20) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpsub2stasub] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 4149(line=189, offs=3) -- 4299(line=195, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpsub_append (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;
ATSlocal (ats_ptr_type, tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpsub_append:
do {
/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_20_0 ; }
__ats_lab_19_1:
tmp29 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_0) ;
tmp30 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_1) ;
tmp31 = ats_caselptrlab_mac(anairiats_sum_4, arg0, atslab_2) ;
tmp32 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpsub_append (tmp31, arg1) ;
tmp28 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
ats_selptrset_mac(anairiats_sum_4, tmp28, atslab_0, tmp29) ;
ats_selptrset_mac(anairiats_sum_4, tmp28, atslab_1, tmp30) ;
ats_selptrset_mac(anairiats_sum_4, tmp28, atslab_2, tmp32) ;
break ;

/* branch: __ats_lab_20 */
__ats_lab_20_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_20_1:
tmp28 = arg1 ;
break ;
} while (0) ;
return (tmp28) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpsub_append] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 5269(line=248, offs=5) -- 7400(line=338, offs=4)
*/
ATSstaticdec()
ats_void_type
aux_11 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;
ATSlocal (ats_ptr_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;
// ATSlocal_void (tmp47) ;
// ATSlocal_void (tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;
ATSlocal (ats_ptr_type, tmp52) ;
// ATSlocal_void (tmp53) ;
// ATSlocal_void (tmp54) ;
// ATSlocal_void (tmp55) ;
// ATSlocal_void (tmp56) ;
ATSlocal (ats_ptr_type, tmp57) ;
ATSlocal (ats_ptr_type, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;
ATSlocal (ats_ptr_type, tmp61) ;
ATSlocal (ats_ptr_type, tmp62) ;
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (ats_ptr_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;
ATSlocal (ats_ptr_type, tmp68) ;
ATSlocal (ats_ptr_type, tmp69) ;
ATSlocal (ats_ptr_type, tmp70) ;
ATSlocal (ats_ptr_type, tmp71) ;
ATSlocal (ats_ptr_type, tmp72) ;
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;
// ATSlocal_void (tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (ats_ptr_type, tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;
ATSlocal (ats_ptr_type, tmp85) ;
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_ptr_type, tmp88) ;
ATSlocal (ats_ptr_type, tmp89) ;
ATSlocal (ats_ptr_type, tmp90) ;
ATSlocal (ats_ptr_type, tmp91) ;
ATSlocal (ats_ptr_type, tmp92) ;
ATSlocal (ats_ptr_type, tmp93) ;

__ats_lab_aux_11:
tmp34 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_5, arg1), atslab_instr_node) ;
do {
/* branch: __ats_lab_21 */
__ats_lab_21_0:
if (((ats_sum_ptr_type)tmp34)->tag != 0) { goto __ats_lab_22_0 ; }
__ats_lab_21_1:
break ;

/* branch: __ats_lab_22 */
__ats_lab_22_0:
if (((ats_sum_ptr_type)tmp34)->tag != 1) { goto __ats_lab_23_0 ; }
__ats_lab_22_1:
break ;

/* branch: __ats_lab_23 */
__ats_lab_23_0:
if (((ats_sum_ptr_type)tmp34)->tag != 2) { goto __ats_lab_24_0 ; }
__ats_lab_23_1:
break ;

/* branch: __ats_lab_24 */
__ats_lab_24_0:
if (((ats_sum_ptr_type)tmp34)->tag != 3) { goto __ats_lab_25_0 ; }
__ats_lab_24_1:
tmp35 = ats_caselptrlab_mac(anairiats_sum_2, tmp34, atslab_0) ;
tmp36 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp35) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp36 ;
break ;

/* branch: __ats_lab_25 */
__ats_lab_25_0:
if (((ats_sum_ptr_type)tmp34)->tag != 4) { goto __ats_lab_26_0 ; }
__ats_lab_25_1:
tmp37 = ats_caselptrlab_mac(anairiats_sum_2, tmp34, atslab_0) ;
tmp38 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp37) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp38 ;
break ;

/* branch: __ats_lab_26 */
__ats_lab_26_0:
if (((ats_sum_ptr_type)tmp34)->tag != 5) { goto __ats_lab_27_0 ; }
__ats_lab_26_1:
break ;

/* branch: __ats_lab_27 */
__ats_lab_27_0:
if (((ats_sum_ptr_type)tmp34)->tag != 6) { goto __ats_lab_28_0 ; }
__ats_lab_27_1:
tmp39 = ats_caselptrlab_mac(anairiats_sum_6, tmp34, atslab_0) ;
tmp40 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp39) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp40 ;
break ;

/* branch: __ats_lab_28 */
__ats_lab_28_0:
if (((ats_sum_ptr_type)tmp34)->tag != 7) { goto __ats_lab_29_0 ; }
__ats_lab_28_1:
tmp41 = ats_caselptrlab_mac(anairiats_sum_7, tmp34, atslab_0) ;
tmp42 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp41) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp42 ;
break ;

/* branch: __ats_lab_29 */
__ats_lab_29_0:
if (((ats_sum_ptr_type)tmp34)->tag != 8) { goto __ats_lab_30_0 ; }
__ats_lab_29_1:
tmp43 = ats_caselptrlab_mac(anairiats_sum_8, tmp34, atslab_0) ;
tmp44 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp43) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp44 ;
break ;

/* branch: __ats_lab_30 */
__ats_lab_30_0:
if (((ats_sum_ptr_type)tmp34)->tag != 9) { goto __ats_lab_31_0 ; }
__ats_lab_30_1:
tmp45 = ats_caselptrlab_mac(anairiats_sum_8, tmp34, atslab_1) ;
tmp46 = ats_caselptrlab_mac(anairiats_sum_8, tmp34, atslab_2) ;
/* tmp47 = */ auxlst_12 (arg0, tmp45) ;
/* tmp48 = */ auxlst_12 (arg0, tmp46) ;
break ;

/* branch: __ats_lab_31 */
__ats_lab_31_0:
if (((ats_sum_ptr_type)tmp34)->tag != 10) { goto __ats_lab_32_0 ; }
__ats_lab_31_1:
break ;

/* branch: __ats_lab_32 */
__ats_lab_32_0:
if (((ats_sum_ptr_type)tmp34)->tag != 11) { goto __ats_lab_33_0 ; }
__ats_lab_32_1:
tmp49 = ats_caselptrlab_mac(anairiats_sum_9, tmp34, atslab_3) ;
tmp50 = ats_caselptrlab_mac(anairiats_sum_9, tmp34, atslab_5) ;
tmp51 = ats_caselptrlab_mac(anairiats_sum_9, tmp34, atslab_6) ;
tmp52 = ats_caselptrlab_mac(anairiats_sum_9, tmp34, atslab_7) ;
/* tmp53 = */ auxlst_12 (arg0, tmp49) ;
/* tmp54 = */ auxlst_12 (arg0, tmp50) ;
/* tmp55 = */ auxlst_12 (arg0, tmp51) ;
/* tmp56 = */ auxlst_12 (arg0, tmp52) ;
break ;

/* branch: __ats_lab_33 */
__ats_lab_33_0:
if (((ats_sum_ptr_type)tmp34)->tag != 12) { goto __ats_lab_34_0 ; }
__ats_lab_33_1:
break ;

/* branch: __ats_lab_34 */
__ats_lab_34_0:
if (((ats_sum_ptr_type)tmp34)->tag != 13) { goto __ats_lab_35_0 ; }
__ats_lab_34_1:
tmp57 = ats_caselptrlab_mac(anairiats_sum_11, tmp34, atslab_0) ;
/* tmp33 = */ auxibrlst_14 (arg0, tmp57) ;
break ;

/* branch: __ats_lab_35 */
__ats_lab_35_0:
if (((ats_sum_ptr_type)tmp34)->tag != 14) { goto __ats_lab_36_0 ; }
__ats_lab_35_1:
break ;

/* branch: __ats_lab_36 */
__ats_lab_36_0:
if (((ats_sum_ptr_type)tmp34)->tag != 15) { goto __ats_lab_37_0 ; }
__ats_lab_36_1:
tmp58 = ats_caselptrlab_mac(anairiats_sum_11, tmp34, atslab_0) ;
/* tmp33 = */ auxpmdlst_16 (arg0, tmp58) ;
break ;

/* branch: __ats_lab_37 */
__ats_lab_37_0:
if (((ats_sum_ptr_type)tmp34)->tag != 16) { goto __ats_lab_38_0 ; }
__ats_lab_37_1:
tmp59 = ats_caselptrlab_mac(anairiats_sum_6, tmp34, atslab_0) ;
tmp60 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp59) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp60 ;
break ;

/* branch: __ats_lab_38 */
__ats_lab_38_0:
if (((ats_sum_ptr_type)tmp34)->tag != 17) { goto __ats_lab_39_0 ; }
__ats_lab_38_1:
tmp61 = ats_caselptrlab_mac(anairiats_sum_2, tmp34, atslab_0) ;
tmp62 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp61) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp62 ;
break ;

/* branch: __ats_lab_39 */
__ats_lab_39_0:
if (((ats_sum_ptr_type)tmp34)->tag != 18) { goto __ats_lab_40_0 ; }
__ats_lab_39_1:
tmp63 = ats_caselptrlab_mac(anairiats_sum_8, tmp34, atslab_0) ;
tmp64 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp63) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp64 ;
break ;

/* branch: __ats_lab_40 */
__ats_lab_40_0:
if (((ats_sum_ptr_type)tmp34)->tag != 19) { goto __ats_lab_41_0 ; }
__ats_lab_40_1:
tmp65 = ats_caselptrlab_mac(anairiats_sum_8, tmp34, atslab_0) ;
tmp66 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp65) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp66 ;
break ;

/* branch: __ats_lab_41 */
__ats_lab_41_0:
if (((ats_sum_ptr_type)tmp34)->tag != 20) { goto __ats_lab_42_0 ; }
__ats_lab_41_1:
break ;

/* branch: __ats_lab_42 */
__ats_lab_42_0:
if (((ats_sum_ptr_type)tmp34)->tag != 21) { goto __ats_lab_43_0 ; }
__ats_lab_42_1:
tmp67 = ats_caselptrlab_mac(anairiats_sum_6, tmp34, atslab_0) ;
tmp68 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp67) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp68 ;
break ;

/* branch: __ats_lab_43 */
__ats_lab_43_0:
if (((ats_sum_ptr_type)tmp34)->tag != 22) { goto __ats_lab_44_0 ; }
__ats_lab_43_1:
break ;

/* branch: __ats_lab_44 */
__ats_lab_44_0:
if (((ats_sum_ptr_type)tmp34)->tag != 23) { goto __ats_lab_45_0 ; }
__ats_lab_44_1:
tmp69 = ats_caselptrlab_mac(anairiats_sum_12, tmp34, atslab_0) ;
tmp70 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp69) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp70 ;
break ;

/* branch: __ats_lab_45 */
__ats_lab_45_0:
if (((ats_sum_ptr_type)tmp34)->tag != 24) { goto __ats_lab_46_0 ; }
__ats_lab_45_1:
break ;

/* branch: __ats_lab_46 */
__ats_lab_46_0:
if (((ats_sum_ptr_type)tmp34)->tag != 25) { goto __ats_lab_47_0 ; }
__ats_lab_46_1:
tmp71 = ats_caselptrlab_mac(anairiats_sum_8, tmp34, atslab_0) ;
tmp72 = ats_caselptrlab_mac(anairiats_sum_8, tmp34, atslab_1) ;
tmp73 = ats_caselptrlab_mac(anairiats_sum_8, tmp34, atslab_2) ;
tmp74 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp71) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp74 ;
/* tmp75 = */ auxlst_12 (arg0, tmp72) ;
/* tmp33 = */ auxibrlst_14 (arg0, tmp73) ;
break ;

/* branch: __ats_lab_47 */
__ats_lab_47_0:
if (((ats_sum_ptr_type)tmp34)->tag != 26) { goto __ats_lab_48_0 ; }
__ats_lab_47_1:
tmp76 = ats_caselptrlab_mac(anairiats_sum_11, tmp34, atslab_0) ;
tmp77 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp76) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp77 ;
break ;

/* branch: __ats_lab_48 */
__ats_lab_48_0:
if (((ats_sum_ptr_type)tmp34)->tag != 27) { goto __ats_lab_49_0 ; }
__ats_lab_48_1:
tmp78 = ats_caselptrlab_mac(anairiats_sum_11, tmp34, atslab_0) ;
tmp79 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp78) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp79 ;
break ;

/* branch: __ats_lab_49 */
__ats_lab_49_0:
if (((ats_sum_ptr_type)tmp34)->tag != 28) { goto __ats_lab_50_0 ; }
__ats_lab_49_1:
tmp80 = ats_caselptrlab_mac(anairiats_sum_2, tmp34, atslab_0) ;
tmp81 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp80) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp81 ;
break ;

/* branch: __ats_lab_50 */
__ats_lab_50_0:
if (((ats_sum_ptr_type)tmp34)->tag != 29) { goto __ats_lab_51_0 ; }
__ats_lab_50_1:
tmp82 = ats_caselptrlab_mac(anairiats_sum_8, tmp34, atslab_0) ;
tmp83 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp82) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp83 ;
break ;

/* branch: __ats_lab_51 */
__ats_lab_51_0:
if (((ats_sum_ptr_type)tmp34)->tag != 30) { goto __ats_lab_52_0 ; }
__ats_lab_51_1:
tmp84 = ats_caselptrlab_mac(anairiats_sum_8, tmp34, atslab_0) ;
tmp85 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp84) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp85 ;
break ;

/* branch: __ats_lab_52 */
__ats_lab_52_0:
if (((ats_sum_ptr_type)tmp34)->tag != 31) { goto __ats_lab_53_0 ; }
__ats_lab_52_1:
tmp86 = ats_caselptrlab_mac(anairiats_sum_2, tmp34, atslab_0) ;
tmp87 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp86) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp87 ;
break ;

/* branch: __ats_lab_53 */
__ats_lab_53_0:
if (((ats_sum_ptr_type)tmp34)->tag != 32) { goto __ats_lab_54_0 ; }
__ats_lab_53_1:
tmp88 = ats_caselptrlab_mac(anairiats_sum_13, tmp34, atslab_0) ;
tmp89 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp88) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp89 ;
break ;

/* branch: __ats_lab_54 */
__ats_lab_54_0:
if (((ats_sum_ptr_type)tmp34)->tag != 33) { goto __ats_lab_55_0 ; }
__ats_lab_54_1:
tmp90 = ats_caselptrlab_mac(anairiats_sum_14, tmp34, atslab_0) ;
tmp91 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp90) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp91 ;
break ;

/* branch: __ats_lab_55 */
__ats_lab_55_0:
if (((ats_sum_ptr_type)tmp34)->tag != 34) { goto __ats_lab_56_0 ; }
__ats_lab_55_1:
break ;

/* branch: __ats_lab_56 */
__ats_lab_56_0:
if (((ats_sum_ptr_type)tmp34)->tag != 35) { goto __ats_lab_57_0 ; }
__ats_lab_56_1:
break ;

/* branch: __ats_lab_57 */
__ats_lab_57_0:
if (((ats_sum_ptr_type)tmp34)->tag != 36) { goto __ats_lab_58_0 ; }
__ats_lab_57_1:
tmp92 = ats_caselptrlab_mac(anairiats_sum_11, tmp34, atslab_0) ;
tmp93 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_add (ats_ptrget_mac(ats_ptr_type, arg0), tmp92) ;
ats_ptrget_mac(ats_ptr_type, arg0) = tmp93 ;
break ;

/* branch: __ats_lab_58 */
__ats_lab_58_0:
// if (((ats_sum_ptr_type)tmp34)->tag != 37) { ats_deadcode_failure_handle () ; }
__ats_lab_58_1:
break ;
} while (0) ;
return /* (tmp33) */ ;
} /* end of [aux_11] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 7422(line=340, offs=5) -- 7630(line=353, offs=4)
*/
ATSstaticdec()
ats_void_type
auxlst_12 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp94) ;
ATSlocal (ats_ptr_type, tmp95) ;
ATSlocal (ats_ptr_type, tmp96) ;
// ATSlocal_void (tmp97) ;

__ats_lab_auxlst_12:
do {
/* branch: __ats_lab_59 */
__ats_lab_59_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_60_0 ; }
__ats_lab_59_1:
tmp95 = ats_caselptrlab_mac(anairiats_sum_15, arg1, atslab_0) ;
tmp96 = ats_caselptrlab_mac(anairiats_sum_15, arg1, atslab_1) ;
/* tmp97 = */ aux_11 (arg0, tmp95) ;
arg0 = arg0 ;
arg1 = tmp96 ;
goto __ats_lab_auxlst_12 ; // tail call
break ;

/* branch: __ats_lab_60 */
__ats_lab_60_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_60_1:
break ;
} while (0) ;
return /* (tmp94) */ ;
} /* end of [auxlst_12] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 7655(line=355, offs=5) -- 7755(line=361, offs=4)
*/
ATSstaticdec()
ats_void_type
auxibr_13 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp98) ;
ATSlocal (ats_ptr_type, tmp99) ;

__ats_lab_auxibr_13:
tmp99 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_16, arg1), atslab_ibranch_inslst) ;
/* tmp98 = */ auxlst_12 (arg0, tmp99) ;
return /* (tmp98) */ ;
} /* end of [auxibr_13] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 7780(line=363, offs=5) -- 8020(line=376, offs=4)
*/
ATSstaticdec()
ats_void_type
auxibrlst_14 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp100) ;
ATSlocal (ats_ptr_type, tmp101) ;
ATSlocal (ats_ptr_type, tmp102) ;
// ATSlocal_void (tmp103) ;

__ats_lab_auxibrlst_14:
do {
/* branch: __ats_lab_61 */
__ats_lab_61_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_62_0 ; }
__ats_lab_61_1:
tmp101 = ats_caselptrlab_mac(anairiats_sum_15, arg1, atslab_0) ;
tmp102 = ats_caselptrlab_mac(anairiats_sum_15, arg1, atslab_1) ;
/* tmp103 = */ auxibr_13 (arg0, tmp101) ;
arg0 = arg0 ;
arg1 = tmp102 ;
goto __ats_lab_auxibrlst_14 ; // tail call
break ;

/* branch: __ats_lab_62 */
__ats_lab_62_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_62_1:
break ;
} while (0) ;
return /* (tmp100) */ ;
} /* end of [auxibrlst_14] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 8048(line=378, offs=5) -- 8967(line=423, offs=4)
*/
ATSstaticdec()
ats_void_type
auxpmd_15 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp104) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;
ATSlocal (ats_ptr_type, tmp107) ;
ATSlocal (ats_ptr_type, tmp108) ;
ATSlocal (ats_ptr_type, tmp109) ;
ATSlocal (ats_ptr_type, tmp110) ;
ATSlocal (ats_ptr_type, tmp111) ;
ATSlocal (ats_ptr_type, tmp112) ;
// ATSlocal_void (tmp113) ;

__ats_lab_auxpmd_15:
tmp105 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_17, arg1), atslab_primdec_node) ;
do {
/* branch: __ats_lab_63 */
__ats_lab_63_0:
if (((ats_sum_ptr_type)tmp105)->tag != 0) { goto __ats_lab_64_0 ; }
__ats_lab_63_1:
break ;

/* branch: __ats_lab_64 */
__ats_lab_64_0:
if (((ats_sum_ptr_type)tmp105)->tag != 1) { goto __ats_lab_65_0 ; }
__ats_lab_64_1:
tmp106 = ats_caselptrlab_mac(anairiats_sum_11, tmp105, atslab_0) ;
/* tmp104 = */ auxpmdlst_16 (arg0, tmp106) ;
break ;

/* branch: __ats_lab_65 */
__ats_lab_65_0:
if (((ats_sum_ptr_type)tmp105)->tag != 2) { goto __ats_lab_66_0 ; }
__ats_lab_65_1:
break ;

/* branch: __ats_lab_66 */
__ats_lab_66_0:
if (((ats_sum_ptr_type)tmp105)->tag != 3) { goto __ats_lab_67_0 ; }
__ats_lab_66_1:
break ;

/* branch: __ats_lab_67 */
__ats_lab_67_0:
if (((ats_sum_ptr_type)tmp105)->tag != 4) { goto __ats_lab_68_0 ; }
__ats_lab_67_1:
break ;

/* branch: __ats_lab_68 */
__ats_lab_68_0:
if (((ats_sum_ptr_type)tmp105)->tag != 9) { goto __ats_lab_69_0 ; }
__ats_lab_68_1:
break ;

/* branch: __ats_lab_69 */
__ats_lab_69_0:
if (((ats_sum_ptr_type)tmp105)->tag != 5) { goto __ats_lab_70_0 ; }
__ats_lab_69_1:
break ;

/* branch: __ats_lab_70 */
__ats_lab_70_0:
if (((ats_sum_ptr_type)tmp105)->tag != 6) { goto __ats_lab_71_0 ; }
__ats_lab_70_1:
tmp107 = ats_caselptrlab_mac(anairiats_sum_8, tmp105, atslab_2) ;
/* tmp104 = */ auxlst_12 (arg0, ats_castfn_mac(ats_ptr_type, tmp107)) ;
break ;

/* branch: __ats_lab_71 */
__ats_lab_71_0:
if (((ats_sum_ptr_type)tmp105)->tag != 7) { goto __ats_lab_72_0 ; }
__ats_lab_71_1:
tmp108 = ats_caselptrlab_mac(anairiats_sum_8, tmp105, atslab_2) ;
/* tmp104 = */ auxlst_12 (arg0, ats_castfn_mac(ats_ptr_type, tmp108)) ;
break ;

/* branch: __ats_lab_72 */
__ats_lab_72_0:
if (((ats_sum_ptr_type)tmp105)->tag != 8) { goto __ats_lab_73_0 ; }
__ats_lab_72_1:
tmp109 = ats_caselptrlab_mac(anairiats_sum_2, tmp105, atslab_1) ;
/* tmp104 = */ auxlst_12 (arg0, ats_castfn_mac(ats_ptr_type, tmp109)) ;
break ;

/* branch: __ats_lab_73 */
__ats_lab_73_0:
if (((ats_sum_ptr_type)tmp105)->tag != 10) { goto __ats_lab_74_0 ; }
__ats_lab_73_1:
tmp110 = ats_caselptrlab_mac(anairiats_sum_11, tmp105, atslab_0) ;
/* tmp104 = */ auxpmdlst_16 (arg0, tmp110) ;
break ;

/* branch: __ats_lab_74 */
__ats_lab_74_0:
if (((ats_sum_ptr_type)tmp105)->tag != 11) { goto __ats_lab_75_0 ; }
__ats_lab_74_1:
break ;

/* branch: __ats_lab_75 */
__ats_lab_75_0:
if (((ats_sum_ptr_type)tmp105)->tag != 12) { goto __ats_lab_76_0 ; }
__ats_lab_75_1:
break ;

/* branch: __ats_lab_76 */
__ats_lab_76_0:
// if (((ats_sum_ptr_type)tmp105)->tag != 13) { ats_deadcode_failure_handle () ; }
__ats_lab_76_1:
tmp111 = ats_caselptrlab_mac(anairiats_sum_2, tmp105, atslab_0) ;
tmp112 = ats_caselptrlab_mac(anairiats_sum_2, tmp105, atslab_1) ;
/* tmp113 = */ auxpmdlst_16 (arg0, tmp111) ;
/* tmp104 = */ auxpmdlst_16 (arg0, tmp112) ;
break ;
} while (0) ;
return /* (tmp104) */ ;
} /* end of [auxpmd_15] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 8992(line=425, offs=5) -- 9223(line=437, offs=4)
*/
ATSstaticdec()
ats_void_type
auxpmdlst_16 (ats_ref_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp114) ;
ATSlocal (ats_ptr_type, tmp115) ;
ATSlocal (ats_ptr_type, tmp116) ;
// ATSlocal_void (tmp117) ;

__ats_lab_auxpmdlst_16:
do {
/* branch: __ats_lab_77 */
__ats_lab_77_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_78_0 ; }
__ats_lab_77_1:
tmp115 = ats_caselptrlab_mac(anairiats_sum_15, arg1, atslab_0) ;
tmp116 = ats_caselptrlab_mac(anairiats_sum_15, arg1, atslab_1) ;
/* tmp117 = */ auxpmd_15 (arg0, tmp115) ;
arg0 = arg0 ;
arg1 = tmp116 ;
goto __ats_lab_auxpmdlst_16 ; // tail call
break ;

/* branch: __ats_lab_78 */
__ats_lab_78_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_78_1:
break ;
} while (0) ;
return /* (tmp114) */ ;
} /* end of [auxpmdlst_16] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 9306(line=443, offs=3) -- 9408(line=451, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__instrlst_get_tmpvarset (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp118) ;
ATSlocal (ats_ptr_type, tmp119) ;
// ATSlocal_void (tmp120) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__instrlst_get_tmpvarset:
/* ats_ptr_type tmp119 ; */
tmp119 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_nil () ;
/* tmp120 = */ auxlst_12 ((&tmp119), arg0) ;
tmp118 = tmp119 ;
return (tmp118) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__instrlst_get_tmpvarset] */

/*
// /home/hwxi/research/Postiats/git/src/pats_ccomp_util.dats: 9482(line=455, offs=3) -- 9587(line=463, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primdeclst_get_tmpvarset (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp121) ;
ATSlocal (ats_ptr_type, tmp122) ;
// ATSlocal_void (tmp123) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primdeclst_get_tmpvarset:
/* ats_ptr_type tmp122 ; */
tmp122 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__tmpvarset_vt_nil () ;
/* tmp123 = */ auxpmdlst_16 ((&tmp122), arg0) ;
tmp121 = tmp122 ;
return (tmp121) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__primdeclst_get_tmpvarset] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2unsafe_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_util_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_util_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_util_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_util_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
// ATS_2d0_2e2_2e10_2prelude_2SATS_2unsafe_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_util_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_util_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_util_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_ccomp_util_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_ccomp_util_dats.c] */
