/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-9-2: 21h:27m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "libc/CATS/stdlib.cats"

#include "libc/CATS/fcntl.cats"

#include "libc/sys/CATS/types.cats"

#include "libats/CATS/linqueue_arr.cats"

#include "libats/ngc/CATS/deque_arr.cats"

#include "libats/CATS/linqueue_arr.cats"

#include "libats/ngc/CATS/deque_arr.cats"

#include "libc/CATS/fcntl.cats"

#include "libc/sys/CATS/types.cats"

#include "libc/CATS/stdio.cats"

#include "libc/sys/CATS/types.cats"

#include "libc/CATS/stdlib.cats"

#include "libc/CATS/fcntl.cats"

#include "libc/sys/CATS/types.cats"

#include "libc/CATS/unistd.cats"

#include "libc/sys/CATS/types.cats"

#include "libc/CATS/fcntl.cats"

#include "libc/sys/CATS/types.cats"
/* external codes at top */
/* type definitions */
typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_0 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_nil_1) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_bool_type, atspre_lt_char_char) (ats_char_type, ats_char_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_char_char) (ats_char_type, ats_char_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_char_char) (ats_char_type, ats_char_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_char_char) (ats_char_type, ats_char_type) ;
ATSextern_fun(ats_bool_type, atspre_char_isdigit) (ats_char_type) ;
ATSextern_fun(ats_char_type, atspre_char_toupper) (ats_char_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_char_char) (ats_char_type, ats_char_type) ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_uint_type, atspre_add_uint_uint) (ats_uint_type, ats_uint_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_llint_type, atspre_llint_of_int) (ats_int_type) ;
ATSextern_fun(ats_llint_type, atspre_mul_llint_llint) (ats_llint_type, ats_llint_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size_size) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gte_size_size) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_size_type, atspre_mul_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, ats_malloc_gc) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_bytes_strbuf_trans) (ats_ptr_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_string_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_fprint_string) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_char_type, atspre_string_get_char_at) (ats_ptr_type, ats_size_type) ;
ATSextern_fun(ats_char_type, atspre_string_get_char_at__intsz) (ats_ptr_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_string_contains) (ats_ptr_type, ats_char_type) ;
ATSextern_fun(ats_size_type, atspre_string_length) (ats_ptr_type) ;
ATSextern_fun(ats_size_type, atspre_string_length) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_string_isnot_empty) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, atspre_string_isnot_atend) (ats_ptr_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_stropt_is_some) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_strptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_tostringf) (ats_ptr_type, ...) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, patsopt_file2strptr) (ats_int_type) ;
ATSextern_fun(ats_int_type, patsopt_strcasecmp) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, patsopt_string_test_prefix) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_bool_type, patsopt_string_test_suffix) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_size_type, ATS_2d0_2e2_2e10_2libats_2ngc_2SATS_2deque_arr_2esats__deque_cap) (ats_ref_type) ;
ATSextern_fun(ats_size_type, ATS_2d0_2e2_2e10_2libats_2ngc_2SATS_2deque_arr_2esats__deque_size) (ats_ref_type) ;
ATSextern_fun(ats_bool_type, ATS_2d0_2e2_2e10_2libats_2ngc_2SATS_2deque_arr_2esats__deque_is_empty) (ats_ref_type) ;
ATSextern_fun(ats_bool_type, ATS_2d0_2e2_2e10_2libats_2ngc_2SATS_2deque_arr_2esats__deque_isnot_empty) (ats_ref_type) ;
ATSextern_fun(ats_bool_type, ATS_2d0_2e2_2e10_2libats_2ngc_2SATS_2deque_arr_2esats__deque_is_full) (ats_ref_type) ;
ATSextern_fun(ats_bool_type, ATS_2d0_2e2_2e10_2libats_2ngc_2SATS_2deque_arr_2esats__deque_isnot_full) (ats_ref_type) ;
ATSextern_fun(ats_void_type, atslib_ngc_deque_arr_deque_initialize_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atslib_ngc_deque_arr_deque_uninitialize) (ats_ref_type) ;
ATSextern_fun(ats_ptr_type, ATS_2d0_2e2_2e10_2libats_2ngc_2SATS_2deque_arr_2esats__deque_uninitialize_vt) (ats_ref_type) ;
ATSextern_fun(ats_ptr_type, atslib_ngc_deque_arr_deque_takeout_tsz) (ats_ref_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_ngc_deque_arr_deque_insert_end_many_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_ngc_deque_arr_deque_remove_beg_many_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_void_type, ATS_2d0_2e2_2e10_2libats_2ngc_2SATS_2deque_arr_2esats__deque_clear_all) (ats_ref_type) ;
ATSextern_fun(ats_void_type, atslib_ngc_deque_arr_deque_copyout_tsz) (ats_ref_type, ats_size_type, ats_size_type, ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atslib_ngc_deque_arr_deque_update_capacity_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2SATS_2deque_arr_2esats__lemma_deque_param_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_v_encode_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_v_decode_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_v_clear_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_insert_beg_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_insert_end_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_remove_beg_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_remove_end_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
extern
ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2edats____assert_prfck () ;
extern
ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__sasp__lstord = 0 ;

/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_char_type ptr0_get_01701_ats_char_type (ats_ptr_type arg0) ;
static
ats_char_type ptrget_01705_ats_char_type (ats_ptr_type arg0) ;
static
ats_int_type loop_2 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_bool_type loop_6 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_llint_type llint_make_string_sgn_8 (ats_int_type arg0, ats_ptr_type arg1, ats_size_type arg2) ;
static
ats_llint_type llint_make_string_sgn_base_9 (ats_int_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_size_type arg3) ;
static
ats_uint_type loop_14 (ats_ptr_type arg0, ats_size_type arg1, ats_uint_type arg2) ;
static
ats_uint_type loop_16 (ats_ptr_type arg0, ats_size_type arg1, ats_uint_type arg2) ;
static
ats_ptr_type aux_20 (ats_ptr_type env0, ats_ptr_type env1, ats_ptr_type arg0) ;
static
ats_clo_ptr_type aux_20_closure_make (ats_ptr_type env0, ats_ptr_type env1) ;
static
ats_ptr_type aux_20_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) ;
static
ats_ptr_type aux_22 (ats_ptr_type env0, ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_clo_ptr_type aux_22_closure_make (ats_ptr_type env0) ;
static
ats_ptr_type aux_22_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_ptr_type aux_24 (ats_ptr_type env0, ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) ;
static
ats_clo_ptr_type aux_24_closure_make (ats_ptr_type env0) ;
static
ats_ptr_type aux_24_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) ;
static
ats_void_type deque_copyout_01866_ats_uchar_type (ats_ref_type arg0, ats_size_type arg1, ats_size_type arg2, ats_ref_type arg3) ;
static
ats_void_type queue_copyout_01747_ats_uchar_type (ats_ref_type arg0, ats_size_type arg1, ats_size_type arg2, ats_ref_type arg3) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 1580(line=47, offs=7) -- 1704(line=52, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__eqref_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp0) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__eqref_type:
tmp0 = atspre_peq (ats_castfn_mac(ats_ptr_type, arg0), ats_castfn_mac(ats_ptr_type, arg1)) ;
return (tmp0) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__eqref_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/unsafe.dats: 1763(line=50, offs=10) -- 1979(line=60, offs=2)
*/
ATSstaticdec()
ats_char_type
ptr0_get_01701_ats_char_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_char_type, tmp6) ;

__ats_lab_ptr0_get_01701_ats_char_type:
tmp6 = ats_ptrget_mac(ats_char_type, ats_castfn_mac(ats_ptr_type, arg0)) ;
return (tmp6) ;
} /* end of [ptr0_get_01701_ats_char_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/unsafe.dats: 2430(line=82, offs=21) -- 2450(line=82, offs=41)
*/
ATSstaticdec()
ats_char_type
ptrget_01705_ats_char_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_char_type, tmp5) ;

__ats_lab_ptrget_01705_ats_char_type:
tmp5 = ptr0_get_01701_ats_char_type (arg0) ;
return (tmp5) ;
} /* end of [ptrget_01705_ats_char_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 1928(line=65, offs=7) -- 2199(line=73, offs=6)
*/
ATSstaticdec()
ats_int_type
loop_2 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp2) ;
ATSlocal (ats_char_type, tmp3) ;
ATSlocal (ats_char_type, tmp4) ;
ATSlocal (ats_char_type, tmp7) ;
ATSlocal (ats_char_type, tmp8) ;
ATSlocal (ats_bool_type, tmp9) ;
ATSlocal (ats_bool_type, tmp10) ;
ATSlocal (ats_bool_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;

__ats_lab_loop_2:
tmp4 = ptrget_01705_ats_char_type (arg0) ;
tmp3 = atspre_char_toupper (tmp4) ;
tmp8 = ptrget_01705_ats_char_type (arg1) ;
tmp7 = atspre_char_toupper (tmp8) ;
tmp9 = atspre_lt_char_char (tmp3, tmp7) ;
if (tmp9) {
tmp2 = -1 ;
} else {
tmp10 = atspre_gt_char_char (tmp3, tmp7) ;
if (tmp10) {
tmp2 = 1 ;
} else {
tmp11 = atspre_neq_char_char (tmp3, '\000') ;
if (tmp11) {
tmp12 = atspre_padd_int (arg0, 1) ;
tmp13 = atspre_padd_int (arg1, 1) ;
arg0 = tmp12 ;
arg1 = tmp13 ;
goto __ats_lab_loop_2 ; // tail call
} else {
tmp2 = 0 ;
} /* end of [if] */
} /* end of [if] */
} /* end of [if] */
return (tmp2) ;
} /* end of [loop_2] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 1907(line=64, offs=12) -- 2284(line=76, offs=4)
*/
ATSglobaldec()
ats_int_type
patsopt_strcasecmp (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_int_type, tmp1) ;

__ats_lab_patsopt_strcasecmp:
tmp1 = loop_2 (ats_castfn_mac(ats_ptr_type, arg0), ats_castfn_mac(ats_ptr_type, arg1)) ;
return (tmp1) ;
} /* end of [patsopt_strcasecmp] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 2516(line=92, offs=5) -- 2737(line=104, offs=4)
*/
ATSstaticdec()
ats_bool_type
loop_6 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp15) ;
ATSlocal (ats_char_type, tmp16) ;
ATSlocal (ats_bool_type, tmp17) ;
ATSlocal (ats_char_type, tmp18) ;
ATSlocal (ats_bool_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;

__ats_lab_loop_6:
tmp16 = ptrget_01705_ats_char_type (arg0) ;
tmp17 = atspre_gt_char_char (tmp16, '\000') ;
if (tmp17) {
tmp18 = ptrget_01705_ats_char_type (arg1) ;
tmp19 = atspre_eq_char_char (tmp16, tmp18) ;
if (tmp19) {
tmp20 = atspre_padd_int (arg0, 1) ;
tmp21 = atspre_padd_int (arg1, 1) ;
arg0 = tmp20 ;
arg1 = tmp21 ;
goto __ats_lab_loop_6 ; // tail call
} else {
tmp15 = ats_false_bool ;
} /* end of [if] */
} else {
tmp15 = ats_true_bool ;
} /* end of [if] */
return (tmp15) ;
} /* end of [loop_6] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 2469(line=88, offs=3) -- 2828(line=108, offs=4)
*/
ATSglobaldec()
ats_bool_type
patsopt_string_test_prefix (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp14) ;

__ats_lab_patsopt_string_test_prefix:
tmp14 = loop_6 (ats_castfn_mac(ats_ptr_type, arg1), ats_castfn_mac(ats_ptr_type, arg0)) ;
return (tmp14) ;
} /* end of [patsopt_string_test_prefix] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 3025(line=120, offs=3) -- 3264(line=134, offs=4)
*/
ATSglobaldec()
ats_bool_type
patsopt_string_test_suffix (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_bool_type, tmp22) ;
ATSlocal (ats_size_type, tmp23) ;
ATSlocal (ats_size_type, tmp24) ;
ATSlocal (ats_bool_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (ats_size_type, tmp27) ;

__ats_lab_patsopt_string_test_suffix:
tmp23 = atspre_string_length (arg0) ;
tmp24 = atspre_string_length (arg1) ;
tmp25 = atspre_gte_size_size (tmp23, tmp24) ;
if (tmp25) {
tmp27 = atspre_sub_size_size (tmp23, tmp24) ;
tmp26 = atspre_padd_size (ats_castfn_mac(ats_ptr_type, arg0), tmp27) ;
tmp22 = atspre_eq_string_string (ats_castfn_mac(ats_ptr_type, tmp26), arg1) ;
} else {
tmp22 = ats_false_bool ;
} /* end of [if] */
return (tmp22) ;
} /* end of [patsopt_string_test_suffix] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 3369(line=143, offs=1) -- 4058(line=167, offs=4)
*/
ATSstaticdec()
ats_llint_type
llint_make_string_sgn_8 (ats_int_type arg0, ats_ptr_type arg1, ats_size_type arg2) {
/* local vardec */
ATSlocal (ats_llint_type, tmp28) ;
ATSlocal (ats_bool_type, tmp29) ;
ATSlocal (ats_char_type, tmp30) ;
ATSlocal (ats_bool_type, tmp31) ;
ATSlocal (ats_size_type, tmp32) ;
ATSlocal (ats_size_type, tmp33) ;
ATSlocal (ats_char_type, tmp34) ;
ATSlocal (ats_bool_type, tmp35) ;
ATSlocal (ats_bool_type, tmp36) ;
ATSlocal (ats_bool_type, tmp37) ;
ATSlocal (ats_size_type, tmp38) ;

__ats_lab_llint_make_string_sgn_8:
tmp29 = atspre_string_isnot_atend (arg1, arg2) ;
if (tmp29) {
tmp30 = atspre_string_get_char_at (arg1, arg2) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (tmp30 != '0') { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp32 = atspre_add_size1_int1 (arg2, 1) ;
tmp31 = atspre_string_isnot_atend (arg1, tmp32) ;
if (tmp31) {
tmp33 = atspre_add_size1_int1 (arg2, 1) ;
tmp34 = atspre_string_get_char_at (arg1, tmp33) ;
tmp36 = atspre_neq_char_char (tmp34, 'x') ;
tmp37 = atspre_neq_char_char (tmp34, 'X') ;
tmp35 = atspre_mul_bool_bool (tmp36, tmp37) ;
if (tmp35) {
tmp28 = llint_make_string_sgn_base_9 (arg0, 8, arg1, tmp33) ;
} else {
tmp38 = atspre_add_size1_int1 (tmp33, 1) ;
tmp28 = llint_make_string_sgn_base_9 (arg0, 16, arg1, tmp38) ;
} /* end of [if] */
} else {
tmp28 = 0ll ;
} /* end of [if] */
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
__ats_lab_1_1:
tmp28 = llint_make_string_sgn_base_9 (arg0, 10, arg1, arg2) ;
break ;
} while (0) ;
} else {
tmp28 = 0ll ;
} /* end of [if] */
return (tmp28) ;
} /* end of [llint_make_string_sgn_8] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 4098(line=170, offs=1) -- 4417(line=182, offs=4)
*/
ATSstaticdec()
ats_llint_type
llint_make_string_sgn_base_9 (ats_int_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_size_type arg3) {
/* local vardec */
ATSlocal (ats_llint_type, tmp39) ;
ATSlocal (ats_llint_type, tmp40) ;
ATSlocal (ats_llint_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;

__ats_lab_llint_make_string_sgn_base_9:
tmp40 = atspre_llint_of_int (arg0) ;
tmp42 = atspre_padd_int (arg2, arg3) ;
tmp41 = atslib_strtoll_errnul (tmp42, arg1) ;
tmp39 = atspre_mul_llint_llint (tmp40, tmp41) ;
return (tmp39) ;
} /* end of [llint_make_string_sgn_base_9] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 4512(line=188, offs=3) -- 4956(line=207, offs=4)
*/
ATSglobaldec()
ats_llint_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__llint_make_string (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_llint_type, tmp43) ;
ATSlocal (ats_int_type, tmp44) ;
ATSlocal (ats_bool_type, tmp45) ;
ATSlocal (ats_char_type, tmp46) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__llint_make_string:
/* ats_int_type tmp44 ; */
tmp44 = 1 ;
tmp45 = atspre_string_isnot_empty (ats_castfn_mac(ats_ptr_type, arg0)) ;
if (tmp45) {
tmp46 = atspre_string_get_char_at__intsz (ats_castfn_mac(ats_ptr_type, arg0), 0) ;
do {
/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (tmp46 != '+') { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp43 = llint_make_string_sgn_8 (1, ats_castfn_mac(ats_ptr_type, arg0), 1) ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (tmp46 != '-') { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp43 = llint_make_string_sgn_8 (-1, ats_castfn_mac(ats_ptr_type, arg0), 1) ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (tmp46 != '~') { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp43 = llint_make_string_sgn_8 (-1, ats_castfn_mac(ats_ptr_type, arg0), 1) ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
__ats_lab_5_1:
tmp43 = llint_make_string_sgn_8 (1, ats_castfn_mac(ats_ptr_type, arg0), 0) ;
break ;
} while (0) ;
} else {
tmp43 = 0ll ;
} /* end of [if] */
return (tmp43) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__llint_make_string] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 5017(line=210, offs=20) -- 5042(line=210, offs=45)
*/
ATSglobaldec()
ats_double_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__double_make_string (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_double_type, tmp47) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__double_make_string:
tmp47 = atslib_atof (arg0) ;
return (tmp47) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__double_make_string] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 5115(line=217, offs=17) -- 5631(line=246, offs=4)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__intrep_get_base (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp48) ;
ATSlocal (ats_bool_type, tmp49) ;
ATSlocal (ats_char_type, tmp50) ;
ATSlocal (ats_bool_type, tmp51) ;
ATSlocal (ats_bool_type, tmp52) ;
ATSlocal (ats_char_type, tmp53) ;
ATSlocal (ats_bool_type, tmp54) ;
ATSlocal (ats_bool_type, tmp55) ;
ATSlocal (ats_bool_type, tmp56) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__intrep_get_base:
tmp49 = atspre_string_isnot_atend (ats_castfn_mac(ats_ptr_type, arg0), 0) ;
if (tmp49) {
tmp50 = atspre_string_get_char_at__intsz (ats_castfn_mac(ats_ptr_type, arg0), 0) ;
tmp51 = atspre_eq_char_char (tmp50, '0') ;
if (tmp51) {
tmp52 = atspre_string_isnot_atend (ats_castfn_mac(ats_ptr_type, arg0), 1) ;
if (tmp52) {
tmp53 = atspre_string_get_char_at__intsz (ats_castfn_mac(ats_ptr_type, arg0), 1) ;
tmp55 = atspre_eq_char_char (tmp53, 'x') ;
if (tmp55) {
tmp54 = ats_true_bool ;
} else {
tmp54 = atspre_eq_char_char (tmp53, 'X') ;
} /* end of [if] */
if (tmp54) {
tmp48 = 16 ;
} else {
tmp56 = atspre_char_isdigit (tmp53) ;
if (tmp56) {
tmp48 = 8 ;
} else {
tmp48 = 10 ;
} /* end of [if] */
} /* end of [if] */
} else {
tmp48 = 10 ;
} /* end of [if] */
} else {
tmp48 = 10 ;
} /* end of [if] */
} else {
tmp48 = 10 ;
} /* end of [if] */
return (tmp48) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__intrep_get_base] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 5805(line=256, offs=5) -- 6022(line=267, offs=4)
*/
ATSstaticdec()
ats_uint_type
loop_14 (ats_ptr_type arg0, ats_size_type arg1, ats_uint_type arg2) {
/* local vardec */
ATSlocal (ats_uint_type, tmp58) ;
ATSlocal (ats_bool_type, tmp59) ;
ATSlocal (ats_size_type, tmp60) ;
ATSlocal (ats_char_type, tmp61) ;
ATSlocal (ats_bool_type, tmp62) ;
ATSlocal (ats_uint_type, tmp63) ;

__ats_lab_loop_14:
tmp59 = atspre_gt_size1_int1 (arg1, 0) ;
if (tmp59) {
tmp60 = atspre_sub_size1_int1 (arg1, 1) ;
tmp61 = atspre_string_get_char_at (arg0, tmp60) ;
tmp62 = atspre_string_contains (ATSstrcst("ulUL"), tmp61) ;
if (tmp62) {
tmp63 = atspre_add_uint_uint (arg2, 1u) ;
arg0 = arg0 ;
arg1 = tmp60 ;
arg2 = tmp63 ;
goto __ats_lab_loop_14 ; // tail call
} else {
tmp58 = arg2 ;
} /* end of [if] */
} else {
tmp58 = arg2 ;
} /* end of [if] */
return (tmp58) ;
} /* end of [loop_14] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 5687(line=249, offs=17) -- 6100(line=273, offs=4)
*/
ATSglobaldec()
ats_uint_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__intrep_get_nsfx (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_uint_type, tmp57) ;
ATSlocal (ats_size_type, tmp64) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__intrep_get_nsfx:
tmp64 = atspre_string_length (ats_castfn_mac(ats_ptr_type, arg0)) ;
tmp57 = loop_14 (ats_castfn_mac(ats_ptr_type, arg0), tmp64, 0u) ;
return (tmp57) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__intrep_get_nsfx] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 6294(line=285, offs=5) -- 6511(line=296, offs=4)
*/
ATSstaticdec()
ats_uint_type
loop_16 (ats_ptr_type arg0, ats_size_type arg1, ats_uint_type arg2) {
/* local vardec */
ATSlocal (ats_uint_type, tmp66) ;
ATSlocal (ats_bool_type, tmp67) ;
ATSlocal (ats_size_type, tmp68) ;
ATSlocal (ats_char_type, tmp69) ;
ATSlocal (ats_bool_type, tmp70) ;
ATSlocal (ats_uint_type, tmp71) ;

__ats_lab_loop_16:
tmp67 = atspre_gt_size1_int1 (arg1, 0) ;
if (tmp67) {
tmp68 = atspre_sub_size1_int1 (arg1, 1) ;
tmp69 = atspre_string_get_char_at (arg0, tmp68) ;
tmp70 = atspre_string_contains (ATSstrcst("fFlL"), tmp69) ;
if (tmp70) {
tmp71 = atspre_add_uint_uint (arg2, 1u) ;
arg0 = arg0 ;
arg1 = tmp68 ;
arg2 = tmp71 ;
goto __ats_lab_loop_16 ; // tail call
} else {
tmp66 = arg2 ;
} /* end of [if] */
} else {
tmp66 = arg2 ;
} /* end of [if] */
return (tmp66) ;
} /* end of [loop_16] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 6176(line=278, offs=16) -- 6589(line=302, offs=4)
*/
ATSglobaldec()
ats_uint_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__float_get_nsfx (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_uint_type, tmp65) ;
ATSlocal (ats_size_type, tmp72) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__float_get_nsfx:
tmp72 = atspre_string_length (ats_castfn_mac(ats_ptr_type, arg0)) ;
tmp65 = loop_16 (ats_castfn_mac(ats_ptr_type, arg0), tmp72, 0u) ;
return (tmp65) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__float_get_nsfx] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 6726(line=313, offs=12) -- 6742(line=313, offs=28)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_nil () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp73) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_nil:
tmp73 = (ats_sum_ptr_type)0 ;
return (tmp73) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_nil] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 6766(line=316, offs=13) -- 6798(line=316, offs=45)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_sing (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp74) ;
ATSlocal (ats_ptr_type, tmp75) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_sing:
tmp75 = (ats_sum_ptr_type)0 ;
tmp74 = ATS_MALLOC(sizeof(anairiats_sum_0)) ;
ats_selptrset_mac(anairiats_sum_0, tmp74, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_0, tmp74, atslab_1, tmp75) ;
return (tmp74) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_sing] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 6855(line=321, offs=7) -- 7124(line=328, offs=46)
*/
ATSstaticdec()
ats_ptr_type
aux_20 (ats_ptr_type env0, ats_ptr_type env1, ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (ats_bool_type, tmp80) ;
ATSlocal (ats_int_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;

__ats_lab_aux_20:
do {
/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp78 = ats_caselptrlab_mac(anairiats_sum_0, arg0, atslab_0) ;
tmp79 = ats_caselptrlab_mac(anairiats_sum_0, arg0, atslab_1) ;
tmp81 = ((ats_int_type(*)(ats_ptr_type, ats_ptr_type))env1) (env0, tmp78) ;
tmp80 = atspre_lte_int_int (tmp81, 0) ;
if (tmp80) {
tmp77 = ATS_MALLOC(sizeof(anairiats_sum_0)) ;
ats_selptrset_mac(anairiats_sum_0, tmp77, atslab_0, env0) ;
ats_selptrset_mac(anairiats_sum_0, tmp77, atslab_1, arg0) ;
} else {
tmp82 = aux_20 (env0, env1, tmp79) ;
tmp77 = ATS_MALLOC(sizeof(anairiats_sum_0)) ;
ats_selptrset_mac(anairiats_sum_0, tmp77, atslab_0, tmp78) ;
ats_selptrset_mac(anairiats_sum_0, tmp77, atslab_1, tmp82) ;
} /* end of [if] */
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_7_1:
tmp83 = (ats_sum_ptr_type)0 ;
tmp77 = ATS_MALLOC(sizeof(anairiats_sum_0)) ;
ats_selptrset_mac(anairiats_sum_0, tmp77, atslab_0, env0) ;
ats_selptrset_mac(anairiats_sum_0, tmp77, atslab_1, tmp83) ;
break ;
} while (0) ;
return (tmp77) ;
} /* end of [aux_20] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
ats_ptr_type closure_env_1 ;
} aux_20_closure_type ;

ats_ptr_type
aux_20_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0) {
return aux_20 (((aux_20_closure_type*)cloptr)->closure_env_0, ((aux_20_closure_type*)cloptr)->closure_env_1, arg0) ;
} /* end of function */

ATSinline()
ats_void_type
aux_20_closure_init (aux_20_closure_type *p_clo, ats_ptr_type env0, ats_ptr_type env1) {
p_clo->closure_fun = (ats_fun_ptr_type)&aux_20_clofun ;
p_clo->closure_env_0 = env0 ;
p_clo->closure_env_1 = env1 ;
return ;
} /* end of function */

ats_clo_ptr_type
aux_20_closure_make (ats_ptr_type env0, ats_ptr_type env1) {
aux_20_closure_type *p_clo = ATS_MALLOC(sizeof(aux_20_closure_type)) ;
aux_20_closure_init (p_clo, env0, env1) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 6829(line=320, offs=3) -- 7160(line=332, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_insert (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp76) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_insert:
tmp76 = aux_20 (arg1, arg2, arg0) ;
return (tmp76) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_insert] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 7244(line=337, offs=7) -- 7690(line=351, offs=25)
*/
ATSstaticdec()
ats_ptr_type
aux_22 (ats_ptr_type env0, ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp85) ;
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;
ATSlocal (ats_ptr_type, tmp88) ;
ATSlocal (ats_ptr_type, tmp89) ;
ATSlocal (ats_bool_type, tmp90) ;
ATSlocal (ats_int_type, tmp91) ;
ATSlocal (ats_ptr_type, tmp92) ;
ATSlocal (ats_ptr_type, tmp93) ;

__ats_lab_aux_22:
do {
/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_11_0 ; }
__ats_lab_8_1:
tmp86 = ats_caselptrlab_mac(anairiats_sum_0, arg0, atslab_0) ;
tmp87 = ats_caselptrlab_mac(anairiats_sum_0, arg0, atslab_1) ;
do {
/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp88 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp89 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
tmp91 = ((ats_int_type(*)(ats_ptr_type, ats_ptr_type))env0) (tmp86, tmp88) ;
tmp90 = atspre_lte_int_int (tmp91, 0) ;
if (tmp90) {
tmp92 = aux_22 (env0, tmp87, arg1) ;
tmp85 = ATS_MALLOC(sizeof(anairiats_sum_0)) ;
ats_selptrset_mac(anairiats_sum_0, tmp85, atslab_0, tmp86) ;
ats_selptrset_mac(anairiats_sum_0, tmp85, atslab_1, tmp92) ;
} else {
tmp93 = aux_22 (env0, arg0, tmp89) ;
tmp85 = ATS_MALLOC(sizeof(anairiats_sum_0)) ;
ats_selptrset_mac(anairiats_sum_0, tmp85, atslab_0, tmp88) ;
ats_selptrset_mac(anairiats_sum_0, tmp85, atslab_1, tmp93) ;
} /* end of [if] */
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_10_1:
tmp85 = arg0 ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_11_1:
tmp85 = arg1 ;
break ;
} while (0) ;
return (tmp85) ;
} /* end of [aux_22] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} aux_22_closure_type ;

ats_ptr_type
aux_22_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0, ats_ptr_type arg1) {
return aux_22 (((aux_22_closure_type*)cloptr)->closure_env_0, arg0, arg1) ;
} /* end of function */

ATSinline()
ats_void_type
aux_22_closure_init (aux_22_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&aux_22_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
aux_22_closure_make (ats_ptr_type env0) {
aux_22_closure_type *p_clo = ATS_MALLOC(sizeof(aux_22_closure_type)) ;
aux_22_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 7216(line=336, offs=3) -- 7732(line=355, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_union (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp84) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_union:
tmp84 = aux_22 (arg2, arg0, arg1) ;
return (tmp84) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_union] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 7814(line=361, offs=5) -- 8230(line=374, offs=61)
*/
ATSstaticdec()
ats_ptr_type
aux_24 (ats_ptr_type env0, ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp95) ;
ATSlocal (ats_ptr_type, tmp96) ;
ATSlocal (ats_ptr_type, tmp97) ;
ATSlocal (ats_bool_type, tmp98) ;
ATSlocal (ats_int_type, tmp99) ;
ATSlocal (ats_int_type, tmp100) ;
ATSlocal (ats_bool_type, tmp101) ;
ATSlocal (ats_ptr_type, tmp102) ;
ATSlocal (ats_bool_type, tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;

__ats_lab_aux_24:
do {
/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
tmp96 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_0) ;
tmp97 = ats_caselptrlab_mac(anairiats_sum_0, arg1, atslab_1) ;
tmp99 = ((ats_int_type(*)(ats_ptr_type, ats_ptr_type))env0) (tmp96, arg0) ;
tmp98 = atspre_eq_int_int (tmp99, 0) ;
if (tmp98) {
tmp100 = atspre_add_int_int (arg2, 1) ;
arg0 = arg0 ;
arg1 = tmp97 ;
arg2 = tmp100 ;
goto __ats_lab_aux_24 ; // tail call
} else {
tmp101 = atspre_gt_int_int (arg2, 0) ;
if (tmp101) {
tmp102 = aux_24 (env0, tmp96, tmp97, 0) ;
tmp95 = ATS_MALLOC(sizeof(anairiats_sum_0)) ;
ats_selptrset_mac(anairiats_sum_0, tmp95, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_0, tmp95, atslab_1, tmp102) ;
} else {
arg0 = tmp96 ;
arg1 = tmp97 ;
arg2 = 0 ;
goto __ats_lab_aux_24 ; // tail call
} /* end of [if] */
} /* end of [if] */
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_13_1:
tmp103 = atspre_gt_int_int (arg2, 0) ;
if (tmp103) {
tmp104 = (ats_sum_ptr_type)0 ;
tmp95 = ATS_MALLOC(sizeof(anairiats_sum_0)) ;
ats_selptrset_mac(anairiats_sum_0, tmp95, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_0, tmp95, atslab_1, tmp104) ;
} else {
tmp95 = (ats_sum_ptr_type)0 ;
} /* end of [if] */
break ;
} while (0) ;
return (tmp95) ;
} /* end of [aux_24] */

typedef struct {
ats_fun_ptr_type closure_fun ;
ats_ptr_type closure_env_0 ;
} aux_24_closure_type ;

ats_ptr_type
aux_24_clofun (ats_clo_ptr_type cloptr, ats_ptr_type arg0, ats_ptr_type arg1, ats_int_type arg2) {
return aux_24 (((aux_24_closure_type*)cloptr)->closure_env_0, arg0, arg1, arg2) ;
} /* end of function */

ATSinline()
ats_void_type
aux_24_closure_init (aux_24_closure_type *p_clo, ats_ptr_type env0) {
p_clo->closure_fun = (ats_fun_ptr_type)&aux_24_clofun ;
p_clo->closure_env_0 = env0 ;
return ;
} /* end of function */

ats_clo_ptr_type
aux_24_closure_make (ats_ptr_type env0) {
aux_24_closure_type *p_clo = ATS_MALLOC(sizeof(aux_24_closure_type)) ;
aux_24_closure_init (p_clo, env0) ;
return (ats_clo_ptr_type)p_clo ;
} /* end of function */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 7791(line=359, offs=7) -- 8373(line=385, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_get_dups (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp94) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_get_dups:
do {
/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
tmp105 = ats_caselptrlab_mac(anairiats_sum_0, arg0, atslab_0) ;
tmp106 = ats_caselptrlab_mac(anairiats_sum_0, arg0, atslab_1) ;
tmp94 = aux_24 (arg1, tmp105, tmp106, 0) ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_15_1:
tmp94 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp94) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord_get_dups] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 8425(line=387, offs=23) -- 8434(line=387, offs=32)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord2list (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp107) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord2list:
tmp107 = arg0 ;
return (tmp107) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__lstord2list] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 8505(line=395, offs=2) -- 8658(line=404, offs=4)
*/
ATSglobaldec()
ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__fprint_stropt (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
// ATSlocal_void (tmp108) ;
ATSlocal (ats_bool_type, tmp109) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__fprint_stropt:
tmp109 = atspre_stropt_is_some (arg1) ;
if (tmp109) {
/* tmp108 = */ atspre_fprint_string (arg0, ats_castfn_mac(ats_ptr_type, arg1)) ;
} else {
/* tmp108 = */ atspre_fprint_string (arg0, ATSstrcst("(none)")) ;
} /* end of [if] */
return /* (tmp108) */ ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__fprint_stropt] */

/*
// /home/hwxi/research/Anairiats/libats/ngc/DATS/deque_arr.dats: 13053(line=506, offs=15) -- 13117(line=507, offs=49)
*/
ATSstaticdec()
ats_void_type
deque_copyout_01866_ats_uchar_type (ats_ref_type arg0, ats_size_type arg1, ats_size_type arg2, ats_ref_type arg3) {
/* local vardec */
// ATSlocal_void (tmp116) ;

__ats_lab_deque_copyout_01866_ats_uchar_type:
/* tmp116 = */ atslib_ngc_deque_arr_deque_copyout_tsz (arg0, arg1, arg2, arg3, sizeof(ats_uchar_type)) ;
return /* (tmp116) */ ;
} /* end of [deque_copyout_01866_ats_uchar_type] */

/*
// /home/hwxi/research/Anairiats/libats/DATS/linqueue_arr.dats: 4066(line=159, offs=3) -- 4113(line=159, offs=50)
*/
ATSstaticdec()
ats_void_type
queue_copyout_01747_ats_uchar_type (ats_ref_type arg0, ats_size_type arg1, ats_size_type arg2, ats_ref_type arg3) {
/* local vardec */
// ATSlocal_void (tmp115) ;

__ats_lab_queue_copyout_01747_ats_uchar_type:
/* tmp115 = */ deque_copyout_01866_ats_uchar_type (arg0, arg1, arg2, arg3) ;
return /* (tmp115) */ ;
} /* end of [queue_copyout_01747_ats_uchar_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_utils.dats: 9703(line=457, offs=3) -- 10206(line=474, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__queue_get_strptr1 (ats_ref_type arg0, ats_size_type arg1, ats_size_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp110) ;
ATSlocal (ats_ptr_type, tmp111) ;
ATSlocal (ats_size_type, tmp112) ;
ATSlocal (ats_ptr_type, tmp113) ;
// ATSlocal_void (tmp114) ;
// ATSlocal_void (tmp117) ;
ATSlocal (ats_ptr_type, tmp118) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__queue_get_strptr1:
tmp112 = atspre_add_size1_int1 (arg2, 1) ;
tmp111 = ats_malloc_gc (tmp112) ;
tmp113 = ats_selsin_mac(tmp111, atslab_2) ;
/* tmp114 = */ queue_copyout_01747_ats_uchar_type (arg0, arg1, arg2, tmp113) ;
/* tmp117 = */ atspre_bytes_strbuf_trans (tmp113, arg2) ;
tmp118 = tmp113 ;
tmp110 = ats_castfn_mac(ats_ptr_type, tmp118) ;
return (tmp110) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__queue_get_strptr1] */

/* static load function */

// extern ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2unsafe_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2unsafe_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2libc_2SATS_2stdlib_2esats__staload (void) ;
// extern ats_void_type ATS_2d0_2e2_2e10_2libats_2SATS_2linqueue_arr_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2libats_2DATS_2linqueue_arr_2edats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2libc_2SATS_2fcntl_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2libc_2SATS_2stdio_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2libc_2SATS_2stdlib_2esats__staload (void) ;
extern ats_void_type ATS_2d0_2e2_2e10_2libc_2SATS_2unistd_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2edats__staload_flag = 1 ;

// ATS_2d0_2e2_2e10_2prelude_2SATS_2unsafe_2esats__staload () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2unsafe_2edats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2esats__staload () ;
ATS_2d0_2e2_2e10_2libc_2SATS_2stdlib_2esats__staload () ;
// ATS_2d0_2e2_2e10_2libats_2SATS_2linqueue_arr_2esats__staload () ;
ATS_2d0_2e2_2e10_2libats_2DATS_2linqueue_arr_2edats__staload () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__staload () ;
ATS_2d0_2e2_2e10_2libc_2SATS_2fcntl_2esats__staload () ;
ATS_2d0_2e2_2e10_2libc_2SATS_2stdio_2esats__staload () ;
ATS_2d0_2e2_2e10_2libc_2SATS_2stdlib_2esats__staload () ;
ATS_2d0_2e2_2e10_2libc_2SATS_2unistd_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e10_2libats_2ngc_2SATS_2deque_arr_2esats__lemma_deque_param_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_v_encode_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_v_decode_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_v_clear_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_insert_beg_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_insert_end_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_remove_beg_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats__DEQUEarr_remove_end_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2libats_2ngc_2DATS_2deque_arr_2edats____assert_prfck () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2edats____assert_prfck () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_utils_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

//
extern
ats_int_type
atslib_fildes_read_all_err
  (ats_int_type fd, ats_ref_type buf, ats_size_type ntot) ;
//
ats_ptr_type
patsopt_file2strptr
  (ats_int_type fd) {
  int err = 0 ;
  int nerr = 0 ;
  char* sbp = (char*)0 ;
//
  long int ofs_beg, ofs_end, nbyte ;
//
  ofs_beg = lseek (fd, 0L, SEEK_CUR) ;
  if (ofs_beg < 0) nerr += 1 ;
  ofs_end = lseek (fd, 0L, SEEK_END) ;
  if (ofs_end < 0) nerr += 1 ;
  ofs_beg = lseek (fd, ofs_beg, SEEK_SET) ;
  if (ofs_beg < 0) nerr += 1 ;
  nbyte = ofs_end - ofs_beg ;
//
  if (nerr == 0) { sbp = ATS_MALLOC(nbyte + 1) ; }
  if (sbp == NULL) nerr += 1 ;
//
  if (nerr == 0) {
    err = atslib_fildes_read_all_err (fd, sbp, nbyte) ;
  }
  if (err < 0) { nerr += 1 ; }
//
  if (nerr == 0) {
    sbp[ofs_end] = '\0'; return sbp ;
  }
//
  if (sbp) free (sbp) ; return NULL ;
} // end of [patsopt_file2strptr]


/* ****** ****** */

/* end of [pats_utils_dats.c] */
