/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-9-2: 15h:46m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef
struct {
ats_ptr_type atslab_hisexp_name ;
ats_ptr_type atslab_hisexp_node ;
} anairiats_rec_1 ;

typedef struct {
ats_int_type atslab_0 ;
ats_int_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_2 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_3 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_4 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_5 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_6 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_7 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_8 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_9 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__None_vt_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__Some_vt_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HITNAM_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSLABELED_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtybox_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtyabs_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEfun_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEcfun_3) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEcst_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEapp_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEextype_6) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSErefarg_7) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtyarr_8) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtyrec_9) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtyrecsin_10) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtysum_11) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtyvar_12) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEvararg_13) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEs2exp_14) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_empty) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_is_boxed) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_is_boxed_fun) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__tyreckind_is_boxed) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__tyreckind_is_flted) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__tyreckind_is_fltext) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2var_get_srt) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__stasub_find) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp_subst_flag) (ats_ptr_type, ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2explst_subst_flag) (ats_ptr_type, ats_ptr_type, ats_ref_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2cstref_get_cst) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2cstref_equ_cst) (ats_ptr_type, ats_ptr_type) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__the_atstkind_t0ype) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__the_bool_t0ype) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__the_size_kind) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__the_atsvoid_t0ype) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tybox) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_void) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_noret) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyabs) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_fun) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cst) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_app) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_extype) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_refarg) (ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyarr) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrecsin) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tysum) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_vararg) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_s2exp) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_make_srtsym) (ats_ptr_type, ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
ATSglobal(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tybox) ;
ATSglobal(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_typtr) ;
ATSglobal(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyclo) ;
ATSglobal(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_funptr) ;
ATSglobal(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cloptr) ;
ATSglobal(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_arrptr) ;
ATSglobal(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_datconptr) ;
ATSglobal(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_datcontyp) ;
ATSglobal(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_exnconptr) ;
ATSglobal(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_undefined) ;

/* internal function declarations */
static
ats_ptr_type hisexp_make_node_12 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_bool_type list_is_sing_01298_ats_ptr_type (ats_ptr_type arg0) ;
static
ats_ptr_type aux_31 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2) ;
static
ats_ptr_type auxlab_32 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2) ;
static
ats_ptr_type auxlst_33 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2) ;
static
ats_ptr_type auxlablst_34 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2) ;
static
ats_ptr_type auxlstlst_35 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2) ;

/* partial value template declarations */
/* static temporary variable declarations */
ATSstatic (ats_ptr_type, statmp0) ;
ATSstatic (ats_ptr_type, statmp1) ;
ATSstatic (ats_ptr_type, statmp2) ;
ATSstatic (ats_ptr_type, statmp3) ;
ATSstatic (ats_ptr_type, statmp4) ;
ATSstatic (ats_ptr_type, statmp5) ;
ATSstatic (ats_ptr_type, statmp6) ;
ATSstatic (ats_ptr_type, statmp7) ;
ATSstatic (ats_ptr_type, statmp8) ;
ATSstatic (ats_ptr_type, statmp9) ;
ATSstatic (ats_ptr_type, statmp10) ;
ATSstatic (ats_ptr_type, statmp11) ;
ATSstatic (ats_ptr_type, statmp12) ;
ATSstatic (ats_ptr_type, statmp13) ;
ATSstatic (ats_ptr_type, statmp14) ;
ATSstatic (ats_ptr_type, statmp15) ;
ATSstatic (ats_ptr_type, statmp16) ;
ATSstatic (ats_ptr_type, statmp17) ;
ATSstatic (ats_ptr_type, statmp18) ;
ATSstatic (ats_ptr_type, statmp19) ;
ATSstatic (ats_ptr_type, statmp20) ;
ATSstatic (ats_ptr_type, statmp52) ;
ATSstatic (ats_ptr_type, statmp53) ;
ATSstatic (ats_ptr_type, statmp54) ;
ATSstatic (ats_ptr_type, statmp55) ;
ATSstatic (ats_ptr_type, statmp56) ;
ATSstatic (ats_ptr_type, statmp57) ;
ATSstatic (ats_ptr_type, statmp58) ;
ATSstatic (ats_ptr_type, statmp59) ;
ATSstatic (ats_ptr_type, statmp60) ;
ATSstatic (ats_ptr_type, statmp61) ;
ATSstatic (ats_ptr_type, statmp62) ;
ATSstatic (ats_ptr_type, statmp63) ;
ATSstatic (ats_ptr_type, statmp64) ;
ATSstatic (ats_ptr_type, statmp65) ;
ATSstatic (ats_ptr_type, statmp66) ;
ATSstatic (ats_ptr_type, statmp67) ;
ATSstatic (ats_ptr_type, statmp68) ;
ATSstatic (ats_ptr_type, statmp69) ;
ATSstatic (ats_ptr_type, statmp70) ;
ATSstatic (ats_ptr_type, statmp71) ;

/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 3488(line=131, offs=3) -- 3690(line=142, offs=4)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_get_boxknd (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;
ATSlocal (ats_bool_type, tmp24) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_get_boxknd:
tmp22 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_hisexp_node) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)tmp22)->tag != 9) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp23 = ats_caselptrlab_mac(anairiats_sum_3, tmp22, atslab_0) ;
tmp24 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__tyreckind_is_boxed (tmp23) ;
if (tmp24) {
tmp21 = 1 ;
} else {
tmp21 = 0 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)tmp22)->tag != 11) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp21 = 0 ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
__ats_lab_2_1:
tmp21 = -1 ;
break ;
} while (0) ;
return (tmp21) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_get_boxknd] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 3752(line=146, offs=3) -- 3900(line=154, offs=4)
*/
ATSglobaldec()
ats_int_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_get_extknd (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_int_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;
ATSlocal (ats_bool_type, tmp28) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_get_extknd:
tmp26 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_hisexp_node) ;
do {
/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)tmp26)->tag != 9) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp27 = ats_caselptrlab_mac(anairiats_sum_3, tmp26, atslab_0) ;
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__tyreckind_is_fltext (tmp27) ;
if (tmp28) {
tmp25 = 1 ;
} else {
tmp25 = 0 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
__ats_lab_4_1:
tmp25 = -1 ;
break ;
} while (0) ;
return (tmp25) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_get_extknd] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 3979(line=159, offs=17) -- 4050(line=161, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_boxed (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp29) ;
ATSlocal (ats_ptr_type, tmp30) ;
ATSlocal (ats_int_type, tmp31) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_boxed:
tmp30 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_hisexp_name) ;

tmp31 = ats_caselptrlab_mac(anairiats_sum_2, tmp30, atslab_0) ;
tmp29 = atspre_gt_int_int (tmp31, 0) ;
return (tmp29) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_boxed] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 4128(line=167, offs=3) -- 4409(line=180, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_void (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp32) ;
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_void:
tmp33 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_hisexp_node) ;
do {
/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)tmp33)->tag != 4) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp34 = ats_caselptrlab_mac(anairiats_sum_4, tmp33, atslab_0) ;
tmp32 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2cstref_equ_cst (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__the_atsvoid_t0ype, tmp34) ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)tmp33)->tag != 10) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp35 = ats_caselptrlab_mac(anairiats_sum_4, tmp33, atslab_0) ;

tmp36 = ats_caselptrlab_mac(anairiats_sum_5, tmp35, atslab_2) ;
arg0 = tmp36 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_void ; // tail call
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
__ats_lab_7_1:
tmp32 = ats_false_bool ;
break ;
} while (0) ;
return (tmp32) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_void] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 4469(line=184, offs=3) -- 4608(line=193, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_fun_is_void (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_fun_is_void:
tmp38 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_hisexp_node) ;
do {
/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)tmp38)->tag != 2) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp39 = ats_caselptrlab_mac(anairiats_sum_6, tmp38, atslab_2) ;
tmp37 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_void (tmp39) ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
__ats_lab_9_1:
tmp37 = ats_false_bool ;
break ;
} while (0) ;
return (tmp37) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_fun_is_void] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 4690(line=199, offs=3) -- 5000(line=214, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_noret (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
ATSlocal (ats_ptr_type, tmp42) ;
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_noret:
tmp41 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_hisexp_node) ;
do {
/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (((ats_sum_ptr_type)tmp41)->tag != 4) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp42 = ats_caselptrlab_mac(anairiats_sum_4, tmp41, atslab_0) ;
tmp40 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2cstref_equ_cst (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__the_atsvoid_t0ype, tmp42) ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (((ats_sum_ptr_type)tmp41)->tag != 12) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp40 = ats_true_bool ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (((ats_sum_ptr_type)tmp41)->tag != 10) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
tmp43 = ats_caselptrlab_mac(anairiats_sum_4, tmp41, atslab_0) ;

tmp44 = ats_caselptrlab_mac(anairiats_sum_5, tmp43, atslab_2) ;
arg0 = tmp44 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_noret ; // tail call
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
__ats_lab_13_1:
tmp40 = ats_false_bool ;
break ;
} while (0) ;
return (tmp40) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_noret] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 5062(line=218, offs=3) -- 5202(line=227, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_fun_is_noret (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp45) ;
ATSlocal (ats_ptr_type, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_fun_is_noret:
tmp46 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_hisexp_node) ;
do {
/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (((ats_sum_ptr_type)tmp46)->tag != 2) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
tmp47 = ats_caselptrlab_mac(anairiats_sum_6, tmp46, atslab_2) ;
tmp45 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_noret (tmp47) ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
__ats_lab_15_1:
tmp45 = ats_false_bool ;
break ;
} while (0) ;
return (tmp45) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_fun_is_noret] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 5285(line=232, offs=20) -- 5365(line=235, offs=4)
*/
ATSglobaldec()
ats_bool_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_tyrecsin (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_tyrecsin:
tmp49 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg0), atslab_hisexp_node) ;
do {
/* branch: __ats_lab_16 */
__ats_lab_16_0:
if (((ats_sum_ptr_type)tmp49)->tag != 10) { goto __ats_lab_17_0 ; }
__ats_lab_16_1:
tmp48 = ats_true_bool ;
break ;

/* branch: __ats_lab_17 */
__ats_lab_17_0:
__ats_lab_17_1:
tmp48 = ats_false_bool ;
break ;
} while (0) ;
return (tmp48) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_is_tyrecsin] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 5447(line=240, offs=19) -- 5509(line=241, offs=54)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__labhisexp_get_elt (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__labhisexp_get_elt:

tmp51 = ats_caselptrlab_mac(anairiats_sum_5, arg0, atslab_2) ;
tmp50 = tmp51 ;
return (tmp50) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__labhisexp_get_elt] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 6905(line=312, offs=19) -- 7058(line=318, offs=6)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_bool_t0ype () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp72) ;
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (ats_ptr_type, tmp74) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_bool_t0ype:
tmp73 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2cstref_get_cst (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__the_bool_t0ype) ;
tmp74 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp74)->tag = 4 ;
ats_selptrset_mac(anairiats_sum_4, tmp74, atslab_0, tmp73) ;
tmp72 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp72, atslab_hisexp_name, statmp9) ;
ats_selptrset_mac(anairiats_rec_1, tmp72, atslab_hisexp_node, tmp74) ;

return (tmp72) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_bool_t0ype] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 7139(line=323, offs=19) -- 7295(line=329, offs=6)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_void_t0ype () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;
ATSlocal (ats_ptr_type, tmp77) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_void_t0ype:
tmp76 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2cstref_get_cst (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__the_atsvoid_t0ype) ;
tmp77 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp77)->tag = 4 ;
ats_selptrset_mac(anairiats_sum_4, tmp77, atslab_0, tmp76) ;
tmp75 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp75, atslab_hisexp_name, statmp9) ;
ats_selptrset_mac(anairiats_rec_1, tmp75, atslab_hisexp_node, tmp77) ;

return (tmp75) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_void_t0ype] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 7376(line=334, offs=19) -- 7613(line=342, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_size_t0ype () {
/* local vardec */
ATSlocal (ats_ptr_type, tmp78) ;
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (ats_ptr_type, tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_ptr_type, tmp84) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_size_t0ype:
tmp79 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2cstref_get_cst (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__the_atstkind_t0ype) ;
tmp80 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cst (tmp79) ;
tmp81 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__s2cstref_get_cst (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__the_size_kind) ;
tmp82 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cst (tmp81) ;
tmp84 = (ats_sum_ptr_type)0 ;
tmp83 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp83, atslab_0, tmp82) ;
ats_selptrset_mac(anairiats_sum_7, tmp83, atslab_1, tmp84) ;
tmp78 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_app (tmp80, tmp83) ;
return (tmp78) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_size_t0ype] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 7670(line=346, offs=5) -- 7777(line=350, offs=2)
*/
ATSstaticdec()
ats_ptr_type
hisexp_make_node_12 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp85) ;

__ats_lab_hisexp_make_node_12:
tmp85 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp85, atslab_hisexp_name, arg0) ;
ats_selptrset_mac(anairiats_rec_1, tmp85, atslab_hisexp_node, arg1) ;

return (tmp85) ;
} /* end of [hisexp_make_node_12] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 7852(line=355, offs=14) -- 7909(line=356, offs=50)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyabs (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp86) ;
ATSlocal (ats_ptr_type, tmp87) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyabs:
tmp87 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp87)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_4, tmp87, atslab_0, arg0) ;
tmp86 = hisexp_make_node_12 (statmp9, tmp87) ;
return (tmp86) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyabs] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 7983(line=362, offs=17) -- 8036(line=363, offs=46)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_make_srt (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp88) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_make_srt:
tmp88 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_make_srtsym (arg0, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_empty) ;
return (tmp88) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_make_srt] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 8099(line=368, offs=3) -- 8213(line=372, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_make_srtsym (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp89) ;
ATSlocal (ats_bool_type, tmp90) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_make_srtsym:
tmp90 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_is_boxed_fun (arg0) ;
if (tmp90) {
tmp89 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tybox ;
} else {
tmp89 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyabs (arg1) ;
} /* end of [if] */
return (tmp89) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_make_srtsym] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 8290(line=378, offs=3) -- 8364(line=379, offs=58)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_fun (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp91) ;
ATSlocal (ats_ptr_type, tmp92) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_fun:
tmp92 = ATS_MALLOC(sizeof(anairiats_sum_6)) ;
((ats_sum_ptr_type)tmp92)->tag = 2 ;
ats_selptrset_mac(anairiats_sum_6, tmp92, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_6, tmp92, atslab_1, arg1) ;
ats_selptrset_mac(anairiats_sum_6, tmp92, atslab_2, arg2) ;
tmp91 = hisexp_make_node_12 (statmp1, tmp92) ;
return (tmp91) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_fun] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 8431(line=385, offs=12) -- 8484(line=385, offs=65)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cst (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp93) ;
ATSlocal (ats_ptr_type, tmp94) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cst:
tmp94 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp94)->tag = 4 ;
ats_selptrset_mac(anairiats_sum_4, tmp94, atslab_0, arg0) ;
tmp93 = hisexp_make_node_12 (statmp9, tmp94) ;
return (tmp93) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cst] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 8530(line=391, offs=3) -- 8597(line=391, offs=70)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_app (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp95) ;
ATSlocal (ats_ptr_type, tmp96) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_app:
tmp96 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp96)->tag = 5 ;
ats_selptrset_mac(anairiats_sum_3, tmp96, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_3, tmp96, atslab_1, arg1) ;
tmp95 = hisexp_make_node_12 (statmp11, tmp96) ;
return (tmp95) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_app] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 8669(line=398, offs=3) -- 8790(line=402, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_extype (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp97) ;
ATSlocal (ats_ptr_type, tmp98) ;
ATSlocal (ats_ptr_type, tmp99) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_extype:
tmp98 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, tmp98, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, tmp98, atslab_1, 1) ;
ats_selptrset_mac(anairiats_sum_2, tmp98, atslab_2, arg0) ;
tmp99 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp99)->tag = 6 ;
ats_selptrset_mac(anairiats_sum_3, tmp99, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_3, tmp99, atslab_1, arg1) ;
tmp97 = hisexp_make_node_12 (tmp98, tmp99) ;
return (tmp97) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_extype] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 8865(line=408, offs=3) -- 9013(line=415, offs=6)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_refarg (ats_int_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp100) ;
ATSlocal (ats_ptr_type, tmp101) ;
ATSlocal (ats_ptr_type, tmp102) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_refarg:
tmp101 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, tmp101, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_2, tmp101, atslab_1, 0) ;
ats_selptrset_mac(anairiats_sum_2, tmp101, atslab_2, ATSstrcst("postiats_refarg")) ;
tmp102 = ATS_MALLOC(sizeof(anairiats_sum_8)) ;
((ats_sum_ptr_type)tmp102)->tag = 7 ;
ats_selptrset_mac(anairiats_sum_8, tmp102, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_8, tmp102, atslab_1, arg1) ;
tmp100 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp100, atslab_hisexp_name, tmp101) ;
ats_selptrset_mac(anairiats_rec_1, tmp100, atslab_hisexp_node, tmp102) ;

return (tmp100) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_refarg] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 9084(line=420, offs=13) -- 9140(line=421, offs=50)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cfun (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cfun:
tmp104 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp104)->tag = 3 ;
ats_selptrset_mac(anairiats_sum_4, tmp104, atslab_0, arg0) ;
tmp103 = hisexp_make_node_12 (statmp2, tmp104) ;
return (tmp103) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cfun] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 9210(line=427, offs=14) -- 9277(line=428, offs=55)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyarr (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyarr:
tmp106 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp106)->tag = 8 ;
ats_selptrset_mac(anairiats_sum_3, tmp106, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_3, tmp106, atslab_1, arg1) ;
tmp105 = hisexp_make_node_12 (statmp13, tmp106) ;
return (tmp105) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyarr] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 9348(line=434, offs=14) -- 9419(line=435, offs=57)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp107) ;
ATSlocal (ats_ptr_type, tmp108) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec:
tmp108 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp108)->tag = 9 ;
ats_selptrset_mac(anairiats_sum_3, tmp108, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_3, tmp108, atslab_1, arg1) ;
tmp107 = hisexp_make_node_12 (statmp14, tmp108) ;
return (tmp107) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 9472(line=439, offs=17) -- 9537(line=440, offs=57)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrecsin (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp109) ;
ATSlocal (ats_ptr_type, tmp110) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrecsin:
tmp110 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp110)->tag = 10 ;
ats_selptrset_mac(anairiats_sum_4, tmp110, atslab_0, arg0) ;
tmp109 = hisexp_make_node_12 (statmp15, tmp110) ;
return (tmp109) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrecsin] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 50922(line=1801, offs=14) -- 50991(line=1803, offs=4)
*/
ATSstaticdec()
ats_bool_type
list_is_sing_01298_ats_ptr_type (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_bool_type, tmp114) ;
ATSlocal (ats_ptr_type, tmp115) ;

__ats_lab_list_is_sing_01298_ats_ptr_type:
do {
/* branch: __ats_lab_18 */
__ats_lab_18_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_19_0 ; }
tmp115 = ats_caselptrlab_mac(anairiats_sum_7, arg0, atslab_1) ;
if (tmp115 != (ats_sum_ptr_type)0) { goto __ats_lab_19_0 ; }
__ats_lab_18_1:
tmp114 = ats_true_bool ;
break ;

/* branch: __ats_lab_19 */
__ats_lab_19_0:
__ats_lab_19_1:
tmp114 = ats_false_bool ;
break ;
} while (0) ;
return (tmp114) ;
} /* end of [list_is_sing_01298_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 9593(line=445, offs=3) -- 9919(line=464, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec2 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp111) ;
ATSlocal (ats_bool_type, tmp112) ;
ATSlocal (ats_bool_type, tmp113) ;
ATSlocal (ats_ptr_type, tmp116) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec2:
tmp112 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__tyreckind_is_flted (arg0) ;
if (tmp112) {
tmp113 = list_is_sing_01298_ats_ptr_type (arg1) ;
if (tmp113) {
// if (arg1 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp116 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_0) ;
tmp111 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrecsin (tmp116) ;
} else {
tmp111 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec (arg0, arg1) ;
} /* end of [if] */
} else {
tmp111 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec (arg0, arg1) ;
} /* end of [if] */
return (tmp111) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec2] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 9991(line=469, offs=14) -- 10062(line=470, offs=57)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tysum (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp117) ;
ATSlocal (ats_ptr_type, tmp118) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tysum:
tmp118 = ATS_MALLOC(sizeof(anairiats_sum_3)) ;
((ats_sum_ptr_type)tmp118)->tag = 11 ;
ats_selptrset_mac(anairiats_sum_3, tmp118, atslab_0, arg0) ;
ats_selptrset_mac(anairiats_sum_3, tmp118, atslab_1, arg1) ;
tmp117 = hisexp_make_node_12 (statmp16, tmp118) ;
return (tmp117) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tysum] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 10133(line=476, offs=14) -- 10350(line=484, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyvar (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp119) ;
ATSlocal (ats_ptr_type, tmp120) ;
ATSlocal (ats_bool_type, tmp121) ;
ATSlocal (ats_ptr_type, tmp122) ;
ATSlocal (ats_ptr_type, tmp123) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyvar:
tmp120 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2var_get_srt (arg0) ;
tmp121 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_is_boxed (tmp120) ;
if (tmp121) {
tmp122 = statmp0 ;
} else {
tmp122 = statmp17 ;
} /* end of [if] */
tmp123 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp123)->tag = 12 ;
ats_selptrset_mac(anairiats_sum_4, tmp123, atslab_0, arg0) ;
tmp119 = hisexp_make_node_12 (tmp122, tmp123) ;
return (tmp119) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyvar] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 10422(line=489, offs=15) -- 10493(line=491, offs=2)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_vararg (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp124) ;
ATSlocal (ats_ptr_type, tmp125) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_vararg:
tmp125 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp125)->tag = 13 ;
ats_selptrset_mac(anairiats_sum_4, tmp125, atslab_0, arg0) ;
tmp124 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, tmp124, atslab_hisexp_name, statmp19) ;
ats_selptrset_mac(anairiats_rec_1, tmp124, atslab_hisexp_node, tmp125) ;

return (tmp124) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_vararg] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 10565(line=496, offs=14) -- 10622(line=497, offs=50)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_s2exp (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp126) ;
ATSlocal (ats_ptr_type, tmp127) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_s2exp:
tmp127 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)tmp127)->tag = 14 ;
ats_selptrset_mac(anairiats_sum_4, tmp127, atslab_0, arg0) ;
tmp126 = hisexp_make_node_12 (statmp20, tmp127) ;
return (tmp126) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_s2exp] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 10681(line=504, offs=5) -- 13176(line=606, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux_31 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp128) ;
ATSlocal (ats_ptr_type, tmp129) ;
ATSlocal (ats_ptr_type, tmp130) ;
ATSlocal (ats_ptr_type, tmp131) ;
ATSlocal (ats_ptr_type, tmp132) ;
ATSlocal (ats_int_type, tmp133) ;
ATSlocal (ats_ptr_type, tmp134) ;
ATSlocal (ats_ptr_type, tmp135) ;
ATSlocal (ats_bool_type, tmp136) ;
ATSlocal (ats_ptr_type, tmp137) ;
ATSlocal (ats_ptr_type, tmp138) ;
ATSlocal (ats_int_type, tmp139) ;
ATSlocal (ats_ptr_type, tmp140) ;
ATSlocal (ats_ptr_type, tmp141) ;
ATSlocal (ats_bool_type, tmp142) ;
ATSlocal (ats_ptr_type, tmp143) ;
ATSlocal (ats_ptr_type, tmp144) ;
ATSlocal (ats_int_type, tmp145) ;
ATSlocal (ats_ptr_type, tmp146) ;
ATSlocal (ats_bool_type, tmp147) ;
ATSlocal (ats_int_type, tmp148) ;
ATSlocal (ats_ptr_type, tmp149) ;
ATSlocal (ats_int_type, tmp150) ;
ATSlocal (ats_ptr_type, tmp151) ;
ATSlocal (ats_bool_type, tmp152) ;
ATSlocal (ats_ptr_type, tmp153) ;
ATSlocal (ats_ptr_type, tmp154) ;
ATSlocal (ats_int_type, tmp155) ;
ATSlocal (ats_ptr_type, tmp156) ;
ATSlocal (ats_ptr_type, tmp157) ;
ATSlocal (ats_bool_type, tmp158) ;
ATSlocal (ats_ptr_type, tmp159) ;
ATSlocal (ats_ptr_type, tmp160) ;
ATSlocal (ats_int_type, tmp161) ;
ATSlocal (ats_ptr_type, tmp162) ;
ATSlocal (ats_bool_type, tmp163) ;
ATSlocal (ats_ptr_type, tmp164) ;
ATSlocal (ats_int_type, tmp165) ;
ATSlocal (ats_ptr_type, tmp166) ;
ATSlocal (ats_bool_type, tmp167) ;
ATSlocal (ats_ptr_type, tmp168) ;
ATSlocal (ats_ptr_type, tmp169) ;
ATSlocal (ats_int_type, tmp170) ;
ATSlocal (ats_ptr_type, tmp171) ;
ATSlocal (ats_bool_type, tmp172) ;
ATSlocal (ats_ptr_type, tmp173) ;
ATSlocal (ats_ptr_type, tmp174) ;
ATSlocal (ats_ptr_type, tmp175) ;
ATSlocal (ats_int_type, tmp176) ;
ATSlocal (ats_ptr_type, tmp177) ;
ATSlocal (ats_int_type, tmp178) ;
ATSlocal (ats_ptr_type, tmp179) ;
ATSlocal (ats_bool_type, tmp180) ;
ATSlocal (ats_ptr_type, tmp181) ;
ATSlocal (ats_int_type, tmp182) ;
ATSlocal (ats_ptr_type, tmp183) ;
ATSlocal (ats_bool_type, tmp184) ;

__ats_lab_aux_31:
tmp129 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_1, arg1), atslab_hisexp_node) ;
do {
/* branch: __ats_lab_20 */
__ats_lab_20_0:
if (((ats_sum_ptr_type)tmp129)->tag != 1) { goto __ats_lab_21_0 ; }
__ats_lab_20_1:
tmp128 = arg1 ;
break ;

/* branch: __ats_lab_21 */
__ats_lab_21_0:
if (((ats_sum_ptr_type)tmp129)->tag != 0) { goto __ats_lab_22_0 ; }
__ats_lab_21_1:
tmp128 = arg1 ;
break ;

/* branch: __ats_lab_22 */
__ats_lab_22_0:
if (((ats_sum_ptr_type)tmp129)->tag != 2) { goto __ats_lab_23_0 ; }
__ats_lab_22_1:
tmp130 = ats_caselptrlab_mac(anairiats_sum_6, tmp129, atslab_0) ;
tmp131 = ats_caselptrlab_mac(anairiats_sum_6, tmp129, atslab_1) ;
tmp132 = ats_caselptrlab_mac(anairiats_sum_6, tmp129, atslab_2) ;
tmp133 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp134 = auxlst_33 (arg0, tmp131, arg2) ;
tmp135 = aux_31 (arg0, tmp132, arg2) ;
tmp136 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp133) ;
if (tmp136) {
tmp128 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_fun (tmp130, tmp134, tmp135) ;
} else {
tmp128 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_23 */
__ats_lab_23_0:
if (((ats_sum_ptr_type)tmp129)->tag != 3) { goto __ats_lab_24_0 ; }
__ats_lab_23_1:
tmp128 = arg1 ;
break ;

/* branch: __ats_lab_24 */
__ats_lab_24_0:
if (((ats_sum_ptr_type)tmp129)->tag != 5) { goto __ats_lab_25_0 ; }
__ats_lab_24_1:
tmp137 = ats_caselptrlab_mac(anairiats_sum_3, tmp129, atslab_0) ;
tmp138 = ats_caselptrlab_mac(anairiats_sum_3, tmp129, atslab_1) ;
tmp139 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp140 = aux_31 (arg0, tmp137, arg2) ;
tmp141 = auxlst_33 (arg0, tmp138, arg2) ;
tmp142 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp139) ;
if (tmp142) {
tmp128 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_app (tmp140, tmp141) ;
} else {
tmp128 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_25 */
__ats_lab_25_0:
if (((ats_sum_ptr_type)tmp129)->tag != 6) { goto __ats_lab_26_0 ; }
__ats_lab_25_1:
tmp143 = ats_caselptrlab_mac(anairiats_sum_3, tmp129, atslab_0) ;
tmp144 = ats_caselptrlab_mac(anairiats_sum_3, tmp129, atslab_1) ;
tmp145 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp146 = auxlstlst_35 (arg0, tmp144, arg2) ;
tmp147 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp145) ;
if (tmp147) {
tmp128 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_extype (tmp143, tmp146) ;
} else {
tmp128 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_26 */
__ats_lab_26_0:
if (((ats_sum_ptr_type)tmp129)->tag != 7) { goto __ats_lab_27_0 ; }
__ats_lab_26_1:
tmp148 = ats_caselptrlab_mac(anairiats_sum_8, tmp129, atslab_0) ;
tmp149 = ats_caselptrlab_mac(anairiats_sum_8, tmp129, atslab_1) ;
tmp150 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp151 = aux_31 (arg0, tmp149, arg2) ;
tmp152 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp150) ;
if (tmp152) {
tmp128 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_refarg (tmp148, tmp151) ;
} else {
tmp128 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_27 */
__ats_lab_27_0:
if (((ats_sum_ptr_type)tmp129)->tag != 8) { goto __ats_lab_28_0 ; }
__ats_lab_27_1:
tmp153 = ats_caselptrlab_mac(anairiats_sum_3, tmp129, atslab_0) ;
tmp154 = ats_caselptrlab_mac(anairiats_sum_3, tmp129, atslab_1) ;
tmp155 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp156 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2explst_subst_flag (arg0, tmp154, arg2) ;
tmp157 = aux_31 (arg0, tmp153, arg2) ;
tmp158 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp155) ;
if (tmp158) {
tmp128 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyarr (tmp157, tmp156) ;
} else {
tmp128 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_28 */
__ats_lab_28_0:
if (((ats_sum_ptr_type)tmp129)->tag != 9) { goto __ats_lab_29_0 ; }
__ats_lab_28_1:
tmp159 = ats_caselptrlab_mac(anairiats_sum_3, tmp129, atslab_0) ;
tmp160 = ats_caselptrlab_mac(anairiats_sum_3, tmp129, atslab_1) ;
tmp161 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp162 = auxlablst_34 (arg0, tmp160, arg2) ;
tmp163 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp161) ;
if (tmp163) {
tmp128 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec (tmp159, tmp162) ;
} else {
tmp128 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_29 */
__ats_lab_29_0:
if (((ats_sum_ptr_type)tmp129)->tag != 10) { goto __ats_lab_30_0 ; }
__ats_lab_29_1:
tmp164 = ats_caselptrlab_mac(anairiats_sum_4, tmp129, atslab_0) ;
tmp165 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp166 = auxlab_32 (arg0, tmp164, arg2) ;
tmp167 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp165) ;
if (tmp167) {
tmp128 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrecsin (tmp166) ;
} else {
tmp128 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_30 */
__ats_lab_30_0:
if (((ats_sum_ptr_type)tmp129)->tag != 11) { goto __ats_lab_31_0 ; }
__ats_lab_30_1:
tmp168 = ats_caselptrlab_mac(anairiats_sum_3, tmp129, atslab_0) ;
tmp169 = ats_caselptrlab_mac(anairiats_sum_3, tmp129, atslab_1) ;
tmp170 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp171 = auxlablst_34 (arg0, tmp169, arg2) ;
tmp172 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp170) ;
if (tmp172) {
tmp128 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tysum (tmp168, tmp171) ;
} else {
tmp128 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_31 */
__ats_lab_31_0:
if (((ats_sum_ptr_type)tmp129)->tag != 12) { goto __ats_lab_34_0 ; }
__ats_lab_31_1:
tmp173 = ats_caselptrlab_mac(anairiats_sum_4, tmp129, atslab_0) ;
tmp174 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__stasub_find (arg0, tmp173) ;
do {
/* branch: __ats_lab_32 */
__ats_lab_32_0:
if (tmp174 == (ats_sum_ptr_type)0) { goto __ats_lab_33_0 ; }
__ats_lab_32_1:
tmp175 = ats_caselptrlab_mac(anairiats_sum_9, tmp174, atslab_0) ;
ATS_FREE(tmp174) ;
tmp176 = atspre_add_int_int (ats_ptrget_mac(ats_int_type, arg2), 1) ;
ats_ptrget_mac(ats_int_type, arg2) = tmp176 ;
tmp128 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_s2exp (tmp175) ;
break ;

/* branch: __ats_lab_33 */
__ats_lab_33_0:
// if (tmp174 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_33_1:
tmp128 = arg1 ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_34 */
__ats_lab_34_0:
if (((ats_sum_ptr_type)tmp129)->tag != 13) { goto __ats_lab_35_0 ; }
__ats_lab_34_1:
tmp177 = ats_caselptrlab_mac(anairiats_sum_4, tmp129, atslab_0) ;
tmp178 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp179 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp_subst_flag (arg0, tmp177, arg2) ;
tmp180 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp178) ;
if (tmp180) {
tmp128 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_vararg (tmp179) ;
} else {
tmp128 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_35 */
__ats_lab_35_0:
if (((ats_sum_ptr_type)tmp129)->tag != 14) { goto __ats_lab_36_0 ; }
__ats_lab_35_1:
tmp181 = ats_caselptrlab_mac(anairiats_sum_4, tmp129, atslab_0) ;
tmp182 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp183 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp_subst_flag (arg0, tmp181, arg2) ;
tmp184 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp182) ;
if (tmp184) {
tmp128 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_s2exp (tmp183) ;
} else {
tmp128 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_36 */
__ats_lab_36_0:
__ats_lab_36_1:
tmp128 = arg1 ;
break ;
} while (0) ;
return (tmp128) ;
} /* end of [aux_31] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 13198(line=608, offs=5) -- 13424(line=616, offs=4)
*/
ATSstaticdec()
ats_ptr_type
auxlab_32 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp185) ;
ATSlocal (ats_int_type, tmp186) ;
ATSlocal (ats_ptr_type, tmp187) ;
ATSlocal (ats_ptr_type, tmp188) ;
ATSlocal (ats_ptr_type, tmp189) ;
ATSlocal (ats_ptr_type, tmp190) ;
ATSlocal (ats_bool_type, tmp191) ;

__ats_lab_auxlab_32:
tmp186 = ats_ptrget_mac(ats_int_type, arg2) ;
// 
tmp187 = ats_caselptrlab_mac(anairiats_sum_5, arg1, atslab_0) ;
tmp188 = ats_caselptrlab_mac(anairiats_sum_5, arg1, atslab_1) ;
tmp189 = ats_caselptrlab_mac(anairiats_sum_5, arg1, atslab_2) ;
tmp190 = aux_31 (arg0, tmp189, arg2) ;
tmp191 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp186) ;
if (tmp191) {
tmp185 = ATS_MALLOC(sizeof(anairiats_sum_5)) ;
ats_selptrset_mac(anairiats_sum_5, tmp185, atslab_0, tmp187) ;
ats_selptrset_mac(anairiats_sum_5, tmp185, atslab_1, tmp188) ;
ats_selptrset_mac(anairiats_sum_5, tmp185, atslab_2, tmp190) ;
} else {
tmp185 = arg1 ;
} /* end of [if] */
return (tmp185) ;
} /* end of [auxlab_32] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 13449(line=618, offs=5) -- 13795(line=634, offs=4)
*/
ATSstaticdec()
ats_ptr_type
auxlst_33 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp192) ;
ATSlocal (ats_ptr_type, tmp193) ;
ATSlocal (ats_ptr_type, tmp194) ;
ATSlocal (ats_int_type, tmp195) ;
ATSlocal (ats_ptr_type, tmp196) ;
ATSlocal (ats_ptr_type, tmp197) ;
ATSlocal (ats_bool_type, tmp198) ;

__ats_lab_auxlst_33:
do {
/* branch: __ats_lab_37 */
__ats_lab_37_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_38_0 ; }
__ats_lab_37_1:
tmp193 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_0) ;
tmp194 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_1) ;
tmp195 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp196 = aux_31 (arg0, tmp193, arg2) ;
tmp197 = auxlst_33 (arg0, tmp194, arg2) ;
tmp198 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp195) ;
if (tmp198) {
tmp192 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp192, atslab_0, tmp196) ;
ats_selptrset_mac(anairiats_sum_7, tmp192, atslab_1, tmp197) ;
} else {
tmp192 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_38 */
__ats_lab_38_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_38_1:
tmp192 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp192) ;
} /* end of [auxlst_33] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 13820(line=636, offs=5) -- 14192(line=652, offs=4)
*/
ATSstaticdec()
ats_ptr_type
auxlablst_34 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp199) ;
ATSlocal (ats_ptr_type, tmp200) ;
ATSlocal (ats_ptr_type, tmp201) ;
ATSlocal (ats_int_type, tmp202) ;
ATSlocal (ats_ptr_type, tmp203) ;
ATSlocal (ats_ptr_type, tmp204) ;
ATSlocal (ats_bool_type, tmp205) ;

__ats_lab_auxlablst_34:
do {
/* branch: __ats_lab_39 */
__ats_lab_39_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_40_0 ; }
__ats_lab_39_1:
tmp200 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_0) ;
tmp201 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_1) ;
tmp202 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp203 = auxlab_32 (arg0, tmp200, arg2) ;
tmp204 = auxlablst_34 (arg0, tmp201, arg2) ;
tmp205 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp202) ;
if (tmp205) {
tmp199 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp199, atslab_0, tmp203) ;
ats_selptrset_mac(anairiats_sum_7, tmp199, atslab_1, tmp204) ;
} else {
tmp199 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_40 */
__ats_lab_40_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_40_1:
tmp199 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp199) ;
} /* end of [auxlablst_34] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 14220(line=654, offs=5) -- 14592(line=670, offs=4)
*/
ATSstaticdec()
ats_ptr_type
auxlstlst_35 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp206) ;
ATSlocal (ats_ptr_type, tmp207) ;
ATSlocal (ats_ptr_type, tmp208) ;
ATSlocal (ats_int_type, tmp209) ;
ATSlocal (ats_ptr_type, tmp210) ;
ATSlocal (ats_ptr_type, tmp211) ;
ATSlocal (ats_bool_type, tmp212) ;

__ats_lab_auxlstlst_35:
do {
/* branch: __ats_lab_41 */
__ats_lab_41_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_42_0 ; }
__ats_lab_41_1:
tmp207 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_0) ;
tmp208 = ats_caselptrlab_mac(anairiats_sum_7, arg1, atslab_1) ;
tmp209 = ats_ptrget_mac(ats_int_type, arg2) ;
tmp210 = auxlst_33 (arg0, tmp207, arg2) ;
tmp211 = auxlstlst_35 (arg0, tmp208, arg2) ;
tmp212 = atspre_gt_int_int (ats_ptrget_mac(ats_int_type, arg2), tmp209) ;
if (tmp212) {
tmp206 = ATS_MALLOC(sizeof(anairiats_sum_7)) ;
ats_selptrset_mac(anairiats_sum_7, tmp206, atslab_0, tmp210) ;
ats_selptrset_mac(anairiats_sum_7, tmp206, atslab_1, tmp211) ;
} else {
tmp206 = arg1 ;
} /* end of [if] */
break ;

/* branch: __ats_lab_42 */
__ats_lab_42_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_42_1:
tmp206 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp206) ;
} /* end of [auxlstlst_35] */

/*
// /home/hwxi/research/Postiats/git/src/pats_histaexp.dats: 14662(line=676, offs=3) -- 14728(line=678, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_subst (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp213) ;
ATSlocal (ats_int_type, tmp214) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_subst:
/* ats_int_type tmp214 ; */
tmp214 = 0 ;
tmp213 = aux_31 (arg0, arg1, (&tmp214)) ;
return (tmp213) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_subst] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_stacst2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */
ATS_GC_MARKROOT(&statmp0, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp1, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp2, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp3, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp4, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp5, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp6, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp7, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp8, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp9, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp10, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp11, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp12, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp13, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp14, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp15, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp16, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp17, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp18, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp19, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp20, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp52, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp53, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp54, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp55, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp56, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp57, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp58, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp59, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp60, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp61, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp62, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp63, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp64, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp65, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp66, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp67, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp68, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp69, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp70, sizeof(ats_ptr_type)) ;
ATS_GC_MARKROOT(&statmp71, sizeof(ats_ptr_type)) ;

/* marking external values for GC */

/* code for dynamic loading */
statmp0 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp0, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp0, atslab_1, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp0, atslab_2, ATSstrcst("atstype_boxed")) ;
statmp1 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp1, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp1, atslab_1, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp1, atslab_2, ATSstrcst("atstype_funptr")) ;
statmp2 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp2, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp2, atslab_1, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp2, atslab_2, ATSstrcst("atstype_cfunptr")) ;
statmp3 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp3, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp3, atslab_1, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp3, atslab_2, ATSstrcst("atstype_cloptr")) ;
statmp4 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp4, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp4, atslab_1, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp4, atslab_2, ATSstrcst("atstype_arrptr")) ;
statmp5 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp5, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp5, atslab_1, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp5, atslab_2, ATSstrcst("atstype_datconptr")) ;
statmp6 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp6, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp6, atslab_1, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp6, atslab_2, ATSstrcst("atstype_datcontyp")) ;
statmp7 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp7, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp7, atslab_1, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp7, atslab_2, ATSstrcst("atstype_exnconptr")) ;
statmp8 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp8, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp8, atslab_1, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp8, atslab_2, ATSstrcst("atst0ype_undefined")) ;
statmp9 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp9, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp9, atslab_1, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp9, atslab_2, ATSstrcst("postiats_tyabs")) ;
statmp10 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp10, atslab_0, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp10, atslab_1, 1) ;
ats_selptrset_mac(anairiats_sum_2, statmp10, atslab_2, ATSstrcst("postiats_typtr")) ;
statmp11 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp11, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp11, atslab_1, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp11, atslab_2, ATSstrcst("postiats_tyapp")) ;
statmp12 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp12, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp12, atslab_1, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp12, atslab_2, ATSstrcst("postiats_tyclo")) ;
statmp13 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp13, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp13, atslab_1, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp13, atslab_2, ATSstrcst("postiats_tyarr")) ;
statmp14 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp14, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp14, atslab_1, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp14, atslab_2, ATSstrcst("postiats_tyrec")) ;
statmp15 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp15, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp15, atslab_1, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp15, atslab_2, ATSstrcst("postiats_tyrecsin")) ;
statmp16 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp16, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp16, atslab_1, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp16, atslab_2, ATSstrcst("postiats_tysum")) ;
statmp17 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp17, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp17, atslab_1, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp17, atslab_2, ATSstrcst("postiats_tyvar")) ;
statmp18 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp18, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp18, atslab_1, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp18, atslab_2, ATSstrcst("postiats_tyvaret")) ;
statmp19 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp19, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp19, atslab_1, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp19, atslab_2, ATSstrcst("postiats_vararg")) ;
statmp20 = ATS_MALLOC(sizeof(anairiats_sum_2)) ;
ats_selptrset_mac(anairiats_sum_2, statmp20, atslab_0, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp20, atslab_1, 0) ;
ats_selptrset_mac(anairiats_sum_2, statmp20, atslab_2, ATSstrcst("postiats_s2exp")) ;
statmp53 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtybox_0) ;
statmp52 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, statmp52, atslab_hisexp_name, statmp0) ;
ats_selptrset_mac(anairiats_rec_1, statmp52, atslab_hisexp_node, statmp53) ;

ATS_GC_MARKROOT(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tybox, sizeof(ats_ptr_type)) ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tybox = statmp52 ;
statmp55 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtybox_0) ;
statmp54 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, statmp54, atslab_hisexp_name, statmp10) ;
ats_selptrset_mac(anairiats_rec_1, statmp54, atslab_hisexp_node, statmp55) ;

ATS_GC_MARKROOT(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_typtr, sizeof(ats_ptr_type)) ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_typtr = statmp54 ;
statmp57 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)statmp57)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_4, statmp57, atslab_0, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_empty) ;
statmp56 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, statmp56, atslab_hisexp_name, statmp12) ;
ats_selptrset_mac(anairiats_rec_1, statmp56, atslab_hisexp_node, statmp57) ;

ATS_GC_MARKROOT(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyclo, sizeof(ats_ptr_type)) ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyclo = statmp56 ;
statmp59 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtybox_0) ;
statmp58 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, statmp58, atslab_hisexp_name, statmp1) ;
ats_selptrset_mac(anairiats_rec_1, statmp58, atslab_hisexp_node, statmp59) ;

ATS_GC_MARKROOT(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_funptr, sizeof(ats_ptr_type)) ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_funptr = statmp58 ;
statmp61 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtybox_0) ;
statmp60 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, statmp60, atslab_hisexp_name, statmp3) ;
ats_selptrset_mac(anairiats_rec_1, statmp60, atslab_hisexp_node, statmp61) ;

ATS_GC_MARKROOT(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cloptr, sizeof(ats_ptr_type)) ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cloptr = statmp60 ;
statmp63 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtybox_0) ;
statmp62 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, statmp62, atslab_hisexp_name, statmp4) ;
ats_selptrset_mac(anairiats_rec_1, statmp62, atslab_hisexp_node, statmp63) ;

ATS_GC_MARKROOT(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_arrptr, sizeof(ats_ptr_type)) ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_arrptr = statmp62 ;
statmp65 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtybox_0) ;
statmp64 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, statmp64, atslab_hisexp_name, statmp5) ;
ats_selptrset_mac(anairiats_rec_1, statmp64, atslab_hisexp_node, statmp65) ;

ATS_GC_MARKROOT(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_datconptr, sizeof(ats_ptr_type)) ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_datconptr = statmp64 ;
statmp67 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtybox_0) ;
statmp66 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, statmp66, atslab_hisexp_name, statmp6) ;
ats_selptrset_mac(anairiats_rec_1, statmp66, atslab_hisexp_node, statmp67) ;

ATS_GC_MARKROOT(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_datcontyp, sizeof(ats_ptr_type)) ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_datcontyp = statmp66 ;
statmp69 = (ats_sum_ptr_type)(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSEtybox_0) ;
statmp68 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, statmp68, atslab_hisexp_name, statmp7) ;
ats_selptrset_mac(anairiats_rec_1, statmp68, atslab_hisexp_node, statmp69) ;

ATS_GC_MARKROOT(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_exnconptr, sizeof(ats_ptr_type)) ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_exnconptr = statmp68 ;
statmp71 = ATS_MALLOC(sizeof(anairiats_sum_4)) ;
((ats_sum_ptr_type)statmp71)->tag = 1 ;
ats_selptrset_mac(anairiats_sum_4, statmp71, atslab_0, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_symbol_2esats__symbol_empty) ;
statmp70 = ATS_MALLOC(sizeof(anairiats_rec_1)) ;
ats_selptrset_mac(anairiats_rec_1, statmp70, atslab_hisexp_name, statmp8) ;
ats_selptrset_mac(anairiats_rec_1, statmp70, atslab_hisexp_node, statmp71) ;

ATS_GC_MARKROOT(&_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_undefined, sizeof(ats_ptr_type)) ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_undefined = statmp70 ;
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_histaexp_dats.c] */
