/*
**
** The C code is generated by ATS/Anairiats
** The compilation time is: 2013-9-3: 17h: 1m
**
*/

/* include some .h files */
#ifndef _ATS_HEADER_NONE
#include "ats_config.h"
#include "ats_basics.h"
#include "ats_types.h"
#include "ats_exception.h"
#include "ats_memory.h"
#endif /* _ATS_HEADER_NONE */

/* include some .cats files */
#ifndef _ATS_PRELUDE_NONE
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/byte.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/sizetype.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/reference.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/lazy.cats"
#include "prelude/CATS/lazy_vt.cats"
#include "prelude/CATS/printf.cats"
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/matrix.cats"
#endif /* _ATS_PRELUDE_NONE */
/* prologues from statically loaded files */

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "libc/CATS/gmp.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_location.cats"

#include "pats_lexbuf.cats"

#include "pats_location.cats"

#include "pats_location.cats"
/* external codes at top */
/* type definitions */
typedef
struct {
ats_ptr_type atslab_3 ;
ats_ptr_type atslab_4 ;
} anairiats_rec_0 ;

typedef
struct {
ats_ptr_type atslab_hisexp_name ;
ats_ptr_type atslab_hisexp_node ;
} anairiats_rec_1 ;

typedef
struct {
ats_ptr_type atslab_s2exp_srt ;
ats_ptr_type atslab_s2exp_node ;
} anairiats_rec_2 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
} anairiats_sum_3 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_4 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_5 ;

typedef struct {
int tag ;
ats_int_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_6 ;

typedef struct {
ats_ptr_type atslab_0 ;
} anairiats_sum_7 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
ats_ptr_type atslab_2 ;
ats_int_type atslab_3 ;
ats_ptr_type atslab_4 ;
ats_ptr_type atslab_5 ;
} anairiats_sum_8 ;

typedef struct {
ats_int_type atslab_0 ;
} anairiats_sum_9 ;

typedef struct {
int tag ;
ats_ptr_type atslab_0 ;
ats_int_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_10 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
} anairiats_sum_11 ;

typedef struct {
ats_ptr_type atslab_0 ;
ats_ptr_type atslab_1 ;
ats_ptr_type atslab_2 ;
} anairiats_sum_12 ;

typedef
struct {
ats_ptr_type atslab_t2mpmarg_loc ;
ats_ptr_type atslab_t2mpmarg_arg ;
} anairiats_rec_13 ;

/* external typedefs */
/* external dynamic constructor declarations */
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_nil_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__None_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__Some_1) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_vt_cons_0) ;
ATSextern_val(ats_sum_type, ATS_2d0_2e2_2e10_2prelude_2basics_sta_2esats__list_vt_nil_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FUNCLOfun_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__FUNCLOclo_1) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__TYRECKINDbox_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__TYRECKINDflt_ext_4) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__SLABELED_0) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Ecst_2) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Evar_5) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Edatcontyp_8) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Edatconptr_9) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Eapp_15) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Elam_16) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Efun_17) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Emetfun_18) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Etop_20) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Ewithout_21) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Etyarr_22) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Etyrec_23) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Einvar_24) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Eexi_25) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Euni_26) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Erefarg_27) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Evararg_28) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__S2Ewth_29) ;
ATSextern_val(ats_sum_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__HSLABELED_0) ;

/* external dynamic constant declarations */
ATSextern_fun(ats_void_type, atspre_vbox_make_view_ptr) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, atspre_add_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_sub_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_lte_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_eq_int_int) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isucc) (ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_iadd) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_isub) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_int_type, atspre_idiv) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_ilt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igt) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_igte) (ats_int_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_size1_of_int1) (ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_add_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_sub_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_size_type, atspre_mul2_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_lt_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_bool_type, atspre_gt_size1_int1) (ats_size_type, ats_int_type) ;
ATSextern_fun(ats_bool_type, atspre_neq_size1_size1) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ptr_alloc_tsz) (ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_ptr_zero_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_ref_make_elt_tsz) (ats_ref_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, ListSubscriptException_make) () ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_alloc_tsz) (ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_free) (ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_funenv_tsz) (ats_ref_type, ats_size_type, ats_ptr_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_initialize_cloenv_tsz) (ats_ref_type, ats_size_type, ats_ref_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_split_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_ptr_type, atspre_array_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type) ;
ATSextern_fun(anairiats_rec_0, atspre_array_ptr_takeout2_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_foreach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_void_type, atspre_array_ptr_iforeach_funenv_tsz) (ats_ref_type, ats_ptr_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, atspre_array2_ptr_takeout_tsz) (ats_ptr_type, ats_size_type, ats_size_type, ats_size_type) ;
ATSextern_fun(ats_void_type, atslib_qsort) (ats_ref_type, ats_size_type, ats_size_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__label_make_int) (ats_int_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_is_prgm) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_is_tkind) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2cst_get_isabs) (ats_ptr_type) ;
ATSextern_fun(ats_bool_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_is_prf) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__t2mpmarg_make) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__stasub_make_nil) () ;
ATSextern_fun(ats_void_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__stasub_free) (ats_ptr_type) ;
ATSextern_fun(ats_int_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__stasub_addlst) (ats_ref_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp_subst) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2explst_mhnfize) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp2hnf) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2hnf2exp) (ats_ptr_type) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tybox) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyclo) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_funptr) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cloptr) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_datconptr) ;
ATSextern_val(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_datcontyp) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_fun) (ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cst) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_app) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_refarg) (ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyarr) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrecsin) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyvar) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_vararg) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_s2exp) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_make_srt) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer) (ats_ptr_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer_shallow) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarg_tyer) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarg_mhnfize) (ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2hnf_tyer) (ats_ptr_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2cst_tyer) (ats_ptr_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_app) (ats_ptr_type, ats_int_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_app2) (ats_ptr_type, ats_int_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_apphnf) (ats_ptr_type, ats_int_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_appcst) (ats_ptr_type, ats_int_type, ats_ptr_type, ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_fun) (ats_ptr_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_tyarr) (ats_ptr_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_tyrec) (ats_ptr_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer) (ats_ptr_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_npf_tyer) (ats_ptr_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_npf_tyer_labize) (ats_ptr_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__labs2explst_tyer) (ats_ptr_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__labs2explst_npf_tyer) (ats_ptr_type, ats_int_type, ats_int_type, ats_ptr_type) ;
ATSextern_fun(ats_ptr_type, _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer_apparg) (ats_ptr_type, ats_ptr_type) ;

/* external dynamic terminating constant declarations */
#ifdef _ATS_PROOFCHECK
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____copy_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____free_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
extern
ats_void_type ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* assuming abstract types */
/* sum constructor declarations */
/* exn constructor declarations */
/* global dynamic (non-functional) constant declarations */
/* internal function declarations */
static
ats_ptr_type auxlst_15 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_int_type arg3) ;
static
ats_ptr_type aux_20 (ats_ptr_type arg0, ats_ptr_type arg1) ;
static
ats_void_type loop_24 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) ;
static
ats_ptr_type list_map_funenv_01412_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) ;
static
ats_ptr_type list_map_fun_01413_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) ;

/* partial value template declarations */
/* static temporary variable declarations */
/* external value variable declarations */

/* function implementations */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 1785(line=64, offs=3) -- 1834(line=64, offs=52)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer_deep (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp0) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer_deep:
tmp0 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, 1, arg1) ;
return (tmp0) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer_deep] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 1895(line=69, offs=3) -- 1944(line=69, offs=52)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer_shallow (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp1) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer_shallow:
tmp1 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, 0, arg1) ;
return (tmp1) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer_shallow] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 3840(line=156, offs=3) -- 3931(line=158, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp2) ;
ATSlocal (ats_ptr_type, tmp3) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer:
tmp3 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp2hnf (arg2) ;
tmp2 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2hnf_tyer (arg0, arg1, tmp3) ;
return (tmp2) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 4000(line=164, offs=3) -- 5304(line=216, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2hnf_tyer (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp4) ;
ATSlocal (ats_ptr_type, tmp5) ;
ATSlocal (ats_ptr_type, tmp6) ;
ATSlocal (ats_ptr_type, tmp7) ;
ATSlocal (ats_ptr_type, tmp8) ;
ATSlocal (ats_ptr_type, tmp9) ;
ATSlocal (ats_ptr_type, tmp10) ;
ATSlocal (ats_ptr_type, tmp11) ;
ATSlocal (ats_ptr_type, tmp12) ;
ATSlocal (ats_ptr_type, tmp13) ;
ATSlocal (ats_ptr_type, tmp14) ;
ATSlocal (ats_ptr_type, tmp15) ;
ATSlocal (ats_ptr_type, tmp16) ;
ATSlocal (ats_ptr_type, tmp17) ;
ATSlocal (ats_ptr_type, tmp18) ;
ATSlocal (ats_int_type, tmp19) ;
ATSlocal (ats_ptr_type, tmp20) ;
ATSlocal (ats_ptr_type, tmp21) ;
ATSlocal (ats_ptr_type, tmp22) ;
ATSlocal (ats_ptr_type, tmp23) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2hnf_tyer:
tmp5 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2hnf2exp (arg2) ;
tmp6 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, tmp5), atslab_s2exp_node) ;
do {
/* branch: __ats_lab_0 */
__ats_lab_0_0:
if (((ats_sum_ptr_type)tmp6)->tag != 2) { goto __ats_lab_1_0 ; }
__ats_lab_0_1:
tmp7 = ats_caselptrlab_mac(anairiats_sum_3, tmp6, atslab_0) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2cst_tyer (arg0, arg1, tmp7) ;
break ;

/* branch: __ats_lab_1 */
__ats_lab_1_0:
if (((ats_sum_ptr_type)tmp6)->tag != 5) { goto __ats_lab_2_0 ; }
__ats_lab_1_1:
tmp8 = ats_caselptrlab_mac(anairiats_sum_3, tmp6, atslab_0) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyvar (tmp8) ;
break ;

/* branch: __ats_lab_2 */
__ats_lab_2_0:
if (((ats_sum_ptr_type)tmp6)->tag != 9) { goto __ats_lab_3_0 ; }
__ats_lab_2_1:
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_datconptr ;
break ;

/* branch: __ats_lab_3 */
__ats_lab_3_0:
if (((ats_sum_ptr_type)tmp6)->tag != 8) { goto __ats_lab_4_0 ; }
__ats_lab_3_1:
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_datcontyp ;
break ;

/* branch: __ats_lab_4 */
__ats_lab_4_0:
if (((ats_sum_ptr_type)tmp6)->tag != 15) { goto __ats_lab_5_0 ; }
__ats_lab_4_1:
tmp9 = ats_caselptrlab_mac(anairiats_sum_4, tmp6, atslab_0) ;
tmp10 = ats_caselptrlab_mac(anairiats_sum_4, tmp6, atslab_1) ;
tmp11 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, tmp5), atslab_s2exp_srt) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_app (arg0, arg1, tmp11, tmp9, tmp10) ;
break ;

/* branch: __ats_lab_5 */
__ats_lab_5_0:
if (((ats_sum_ptr_type)tmp6)->tag != 16) { goto __ats_lab_6_0 ; }
__ats_lab_5_1:
tmp12 = ats_caselptrlab_mac(anairiats_sum_4, tmp6, atslab_1) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, arg1, tmp12) ;
break ;

/* branch: __ats_lab_6 */
__ats_lab_6_0:
if (((ats_sum_ptr_type)tmp6)->tag != 17) { goto __ats_lab_7_0 ; }
__ats_lab_6_1:
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_fun (arg0, arg1, tmp5) ;
break ;

/* branch: __ats_lab_7 */
__ats_lab_7_0:
if (((ats_sum_ptr_type)tmp6)->tag != 18) { goto __ats_lab_8_0 ; }
__ats_lab_7_1:
tmp13 = ats_caselptrlab_mac(anairiats_sum_5, tmp6, atslab_2) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, arg1, tmp13) ;
break ;

/* branch: __ats_lab_8 */
__ats_lab_8_0:
if (((ats_sum_ptr_type)tmp6)->tag != 20) { goto __ats_lab_9_0 ; }
__ats_lab_8_1:
tmp14 = ats_caselptrlab_mac(anairiats_sum_6, tmp6, atslab_1) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, arg1, tmp14) ;
break ;

/* branch: __ats_lab_9 */
__ats_lab_9_0:
if (((ats_sum_ptr_type)tmp6)->tag != 21) { goto __ats_lab_10_0 ; }
__ats_lab_9_1:
tmp15 = ats_caselptrlab_mac(anairiats_sum_3, tmp6, atslab_0) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, arg1, tmp15) ;
break ;

/* branch: __ats_lab_10 */
__ats_lab_10_0:
if (((ats_sum_ptr_type)tmp6)->tag != 22) { goto __ats_lab_11_0 ; }
__ats_lab_10_1:
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_tyarr (arg0, arg1, tmp5) ;
break ;

/* branch: __ats_lab_11 */
__ats_lab_11_0:
if (((ats_sum_ptr_type)tmp6)->tag != 23) { goto __ats_lab_12_0 ; }
__ats_lab_11_1:
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_tyrec (arg0, arg1, tmp5) ;
break ;

/* branch: __ats_lab_12 */
__ats_lab_12_0:
if (((ats_sum_ptr_type)tmp6)->tag != 24) { goto __ats_lab_13_0 ; }
__ats_lab_12_1:
tmp16 = ats_caselptrlab_mac(anairiats_sum_3, tmp6, atslab_0) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, arg1, tmp16) ;
break ;

/* branch: __ats_lab_13 */
__ats_lab_13_0:
if (((ats_sum_ptr_type)tmp6)->tag != 25) { goto __ats_lab_14_0 ; }
__ats_lab_13_1:
tmp17 = ats_caselptrlab_mac(anairiats_sum_5, tmp6, atslab_2) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, arg1, tmp17) ;
break ;

/* branch: __ats_lab_14 */
__ats_lab_14_0:
if (((ats_sum_ptr_type)tmp6)->tag != 26) { goto __ats_lab_15_0 ; }
__ats_lab_14_1:
tmp18 = ats_caselptrlab_mac(anairiats_sum_5, tmp6, atslab_2) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, arg1, tmp18) ;
break ;

/* branch: __ats_lab_15 */
__ats_lab_15_0:
if (((ats_sum_ptr_type)tmp6)->tag != 27) { goto __ats_lab_16_0 ; }
__ats_lab_15_1:
tmp19 = ats_caselptrlab_mac(anairiats_sum_6, tmp6, atslab_0) ;
tmp20 = ats_caselptrlab_mac(anairiats_sum_6, tmp6, atslab_1) ;
tmp21 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer_shallow (arg0, tmp20) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_refarg (tmp19, tmp21) ;
break ;

/* branch: __ats_lab_16 */
__ats_lab_16_0:
if (((ats_sum_ptr_type)tmp6)->tag != 28) { goto __ats_lab_17_0 ; }
__ats_lab_16_1:
tmp22 = ats_caselptrlab_mac(anairiats_sum_3, tmp6, atslab_0) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_vararg (tmp22) ;
break ;

/* branch: __ats_lab_17 */
__ats_lab_17_0:
if (((ats_sum_ptr_type)tmp6)->tag != 29) { goto __ats_lab_18_0 ; }
__ats_lab_17_1:
tmp23 = ats_caselptrlab_mac(anairiats_sum_4, tmp6, atslab_0) ;
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, arg1, tmp23) ;
break ;

/* branch: __ats_lab_18 */
__ats_lab_18_0:
__ats_lab_18_1:
tmp4 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_s2exp (tmp5) ;
break ;
} while (0) ;
return (tmp4) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2hnf_tyer] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 5373(line=222, offs=3) -- 5650(line=238, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2cst_tyer (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp24) ;
ATSlocal (ats_ptr_type, tmp25) ;
ATSlocal (ats_ptr_type, tmp26) ;
ATSlocal (ats_ptr_type, tmp27) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2cst_tyer:
tmp25 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2cst_get_isabs (arg2) ;
do {
/* branch: __ats_lab_19 */
__ats_lab_19_0:
if (tmp25 == (ats_sum_ptr_type)0) { goto __ats_lab_22_0 ; }
__ats_lab_19_1:
tmp26 = ats_caselptrlab_mac(anairiats_sum_7, tmp25, atslab_0) ;
do {
/* branch: __ats_lab_20 */
__ats_lab_20_0:
if (tmp26 == (ats_sum_ptr_type)0) { goto __ats_lab_21_0 ; }
__ats_lab_20_1:
tmp27 = ats_caselptrlab_mac(anairiats_sum_7, tmp26, atslab_0) ;
tmp24 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, arg1, tmp27) ;
break ;

/* branch: __ats_lab_21 */
__ats_lab_21_0:
// if (tmp26 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_21_1:
tmp24 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cst (arg2) ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_22 */
__ats_lab_22_0:
// if (tmp25 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_22_1:
tmp24 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cst (arg2) ;
break ;
} while (0) ;
return (tmp24) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2cst_tyer] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 5721(line=243, offs=16) -- 6047(line=257, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_app (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp28) ;
ATSlocal (ats_ptr_type, tmp29) ;
ATSlocal (ats_ptr_type, tmp30) ;
ATSlocal (ats_ptr_type, tmp31) ;
ATSlocal (ats_ptr_type, tmp32) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_app:
tmp29 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp2hnf (arg3) ;
tmp30 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2hnf2exp (tmp29) ;
tmp31 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, tmp30), atslab_s2exp_node) ;
do {
/* branch: __ats_lab_23 */
__ats_lab_23_0:
if (((ats_sum_ptr_type)tmp31)->tag != 2) { goto __ats_lab_24_0 ; }
__ats_lab_23_1:
tmp32 = ats_caselptrlab_mac(anairiats_sum_3, tmp31, atslab_0) ;
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_appcst (arg0, arg1, arg2, tmp32, arg4) ;
break ;

/* branch: __ats_lab_24 */
__ats_lab_24_0:
__ats_lab_24_1:
tmp28 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_apphnf (arg0, arg1, arg2, tmp29, arg4) ;
break ;
} while (0) ;
return (tmp28) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_app] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 6102(line=260, offs=17) -- 6768(line=290, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_app2 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp33) ;
ATSlocal (ats_ptr_type, tmp34) ;
ATSlocal (ats_ptr_type, tmp35) ;
ATSlocal (ats_ptr_type, tmp36) ;
ATSlocal (ats_ptr_type, tmp37) ;
ATSlocal (ats_ptr_type, tmp38) ;
ATSlocal (ats_ptr_type, tmp39) ;
ATSlocal (ats_int_type, tmp40) ;
ATSlocal (ats_ptr_type, tmp41) ;
// ATSlocal_void (tmp42) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_app2:
tmp34 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp2hnf (arg3) ;
tmp35 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2hnf2exp (tmp34) ;
tmp36 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, tmp35), atslab_s2exp_node) ;
do {
/* branch: __ats_lab_25 */
__ats_lab_25_0:
if (((ats_sum_ptr_type)tmp36)->tag != 16) { goto __ats_lab_26_0 ; }
__ats_lab_25_1:
tmp37 = ats_caselptrlab_mac(anairiats_sum_4, tmp36, atslab_0) ;
tmp38 = ats_caselptrlab_mac(anairiats_sum_4, tmp36, atslab_1) ;
/* ats_ptr_type tmp39 ; */
tmp39 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__stasub_make_nil () ;
tmp40 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__stasub_addlst ((&tmp39), tmp37, arg4) ;
tmp41 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2exp_subst (tmp39, tmp38) ;
/* tmp42 = */ _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__stasub_free (tmp39) ;
tmp33 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, arg1, tmp41) ;
break ;

/* branch: __ats_lab_26 */
__ats_lab_26_0:
__ats_lab_26_1:
tmp33 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_apphnf (arg0, arg1, arg2, tmp34, arg4) ;
break ;
} while (0) ;
return (tmp33) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_app2] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 6847(line=295, offs=19) -- 7038(line=302, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_apphnf (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp43) ;
ATSlocal (ats_ptr_type, tmp44) ;
ATSlocal (ats_ptr_type, tmp45) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_apphnf:
tmp44 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2hnf_tyer (arg0, arg1, arg3) ;
tmp45 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer_apparg (arg0, arg4) ;
tmp43 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_app (tmp44, tmp45) ;
return (tmp43) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_apphnf] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 7119(line=307, offs=19) -- 7618(line=329, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_appcst (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_ptr_type arg3, ats_ptr_type arg4) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp46) ;
ATSlocal (ats_ptr_type, tmp47) ;
ATSlocal (ats_ptr_type, tmp48) ;
ATSlocal (ats_ptr_type, tmp49) ;
ATSlocal (ats_ptr_type, tmp50) ;
ATSlocal (ats_ptr_type, tmp51) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_appcst:
tmp47 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2cst_get_isabs (arg3) ;
do {
/* branch: __ats_lab_27 */
__ats_lab_27_0:
if (tmp47 == (ats_sum_ptr_type)0) { goto __ats_lab_30_0 ; }
__ats_lab_27_1:
tmp48 = ats_caselptrlab_mac(anairiats_sum_7, tmp47, atslab_0) ;
do {
/* branch: __ats_lab_28 */
__ats_lab_28_0:
if (tmp48 == (ats_sum_ptr_type)0) { goto __ats_lab_29_0 ; }
__ats_lab_28_1:
tmp49 = ats_caselptrlab_mac(anairiats_sum_7, tmp48, atslab_0) ;
tmp46 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_app2 (arg0, arg1, arg2, tmp49, arg4) ;
break ;

/* branch: __ats_lab_29 */
__ats_lab_29_0:
// if (tmp48 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_29_1:
tmp50 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2cst_tyer (arg0, arg1, arg3) ;
tmp51 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer_apparg (arg0, arg4) ;
tmp46 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_app (tmp50, tmp51) ;
break ;
} while (0) ;
break ;

/* branch: __ats_lab_30 */
__ats_lab_30_0:
// if (tmp47 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_30_1:
tmp46 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_make_srt (arg2) ;
break ;
} while (0) ;
return (tmp46) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_appcst] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 7698(line=335, offs=3) -- 8169(line=357, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_fun (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp52) ;
ATSlocal (ats_ptr_type, tmp53) ;
ATSlocal (ats_ptr_type, tmp54) ;
ATSlocal (ats_int_type, tmp55) ;
ATSlocal (ats_ptr_type, tmp56) ;
ATSlocal (ats_ptr_type, tmp57) ;
ATSlocal (ats_bool_type, tmp58) ;
ATSlocal (ats_ptr_type, tmp59) ;
ATSlocal (ats_ptr_type, tmp60) ;
ATSlocal (ats_int_type, tmp61) ;
ATSlocal (ats_bool_type, tmp62) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_fun:
tmp53 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, arg2), atslab_s2exp_node) ;
if (((ats_sum_ptr_type)tmp53)->tag != 17) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 7730(line=337, offs=5) -- 7798(line=339, offs=20)") ; }
tmp54 = ats_caselptrlab_mac(anairiats_sum_8, tmp53, atslab_0) ;
tmp55 = ats_caselptrlab_mac(anairiats_sum_8, tmp53, atslab_3) ;
tmp56 = ats_caselptrlab_mac(anairiats_sum_8, tmp53, atslab_4) ;
tmp57 = ats_caselptrlab_mac(anairiats_sum_8, tmp53, atslab_5) ;
tmp58 = atspre_gt_int_int (arg1, 0) ;
if (tmp58) {
tmp59 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_npf_tyer (arg0, tmp55, tmp56) ;
tmp60 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer_shallow (arg0, tmp57) ;
tmp52 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_fun (tmp54, tmp59, tmp60) ;
} else {
do {
/* branch: __ats_lab_31 */
__ats_lab_31_0:
if (tmp54 != (ats_sum_ptr_type)0) { goto __ats_lab_32_0 ; }
__ats_lab_31_1:
tmp52 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_funptr ;
break ;

/* branch: __ats_lab_32 */
__ats_lab_32_0:
// if (tmp54 == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_32_1:
tmp61 = ats_caselptrlab_mac(anairiats_sum_9, tmp54, atslab_0) ;
tmp62 = atspre_eq_int_int (tmp61, 0) ;
if (tmp62) {
tmp52 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyclo ;
} else {
tmp52 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_cloptr ;
} /* end of [if] */
break ;
} while (0) ;
} /* end of [if] */
return (tmp52) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_fun] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 8248(line=363, offs=3) -- 8410(line=369, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_tyarr (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp63) ;
ATSlocal (ats_ptr_type, tmp64) ;
ATSlocal (ats_ptr_type, tmp65) ;
ATSlocal (ats_ptr_type, tmp66) ;
ATSlocal (ats_ptr_type, tmp67) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_tyarr:
tmp64 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, arg2), atslab_s2exp_node) ;
if (((ats_sum_ptr_type)tmp64)->tag != 22) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 8279(line=364, offs=7) -- 8324(line=365, offs=37)") ; }
tmp65 = ats_caselptrlab_mac(anairiats_sum_4, tmp64, atslab_0) ;
tmp66 = ats_caselptrlab_mac(anairiats_sum_4, tmp64, atslab_1) ;
tmp67 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, arg1, tmp65) ;
tmp63 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyarr (tmp67, tmp66) ;
return (tmp63) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_tyarr] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 8470(line=373, offs=3) -- 9033(line=396, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_tyrec (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp68) ;
ATSlocal (ats_ptr_type, tmp69) ;
ATSlocal (ats_ptr_type, tmp70) ;
ATSlocal (ats_int_type, tmp71) ;
ATSlocal (ats_ptr_type, tmp72) ;
ATSlocal (ats_ptr_type, tmp73) ;
ATSlocal (ats_bool_type, tmp74) ;
ATSlocal (ats_ptr_type, tmp75) ;
ATSlocal (ats_ptr_type, tmp76) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_tyrec:
tmp69 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, arg2), atslab_s2exp_node) ;
if (((ats_sum_ptr_type)tmp69)->tag != 23) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 8501(line=374, offs=7) -- 8549(line=375, offs=40)") ; }
tmp70 = ats_caselptrlab_mac(anairiats_sum_10, tmp69, atslab_0) ;
tmp71 = ats_caselptrlab_mac(anairiats_sum_10, tmp69, atslab_1) ;
tmp72 = ats_caselptrlab_mac(anairiats_sum_10, tmp69, atslab_2) ;
tmp73 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__labs2explst_npf_tyer (arg0, arg1, tmp71, tmp72) ;
do {
/* branch: __ats_lab_33 */
__ats_lab_33_0:
if (((ats_sum_ptr_type)tmp70)->tag != 0) { goto __ats_lab_34_0 ; }
__ats_lab_33_1:
tmp74 = atspre_gt_int_int (arg1, 0) ;
if (tmp74) {
tmp68 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec (tmp70, tmp73) ;
} else {
tmp68 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tybox ;
} /* end of [if] */
break ;

/* branch: __ats_lab_34 */
__ats_lab_34_0:
if (((ats_sum_ptr_type)tmp70)->tag != 4) { goto __ats_lab_35_0 ; }
__ats_lab_34_1:
tmp68 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec (tmp70, tmp73) ;
break ;

/* branch: __ats_lab_35 */
__ats_lab_35_0:
__ats_lab_35_1:
do {
/* branch: __ats_lab_36 */
__ats_lab_36_0:
if (tmp73 == (ats_sum_ptr_type)0) { goto __ats_lab_37_0 ; }
tmp75 = ats_caselptrlab_mac(anairiats_sum_11, tmp73, atslab_1) ;
if (tmp75 != (ats_sum_ptr_type)0) { goto __ats_lab_37_0 ; }
__ats_lab_36_1:
tmp76 = ats_caselptrlab_mac(anairiats_sum_11, tmp73, atslab_0) ;
tmp68 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrecsin (tmp76) ;
break ;

/* branch: __ats_lab_37 */
__ats_lab_37_0:
__ats_lab_37_1:
tmp68 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__hisexp_tyrec (tmp70, tmp73) ;
break ;
} while (0) ;
break ;
} while (0) ;
return (tmp68) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2exp_tyer_tyrec] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 9111(line=402, offs=3) -- 9531(line=423, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp77) ;
ATSlocal (ats_ptr_type, tmp78) ;
ATSlocal (ats_ptr_type, tmp79) ;
ATSlocal (ats_bool_type, tmp80) ;
ATSlocal (ats_ptr_type, tmp81) ;
ATSlocal (ats_ptr_type, tmp82) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer:
do {
/* branch: __ats_lab_38 */
__ats_lab_38_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_39_0 ; }
__ats_lab_38_1:
tmp78 = ats_caselptrlab_mac(anairiats_sum_11, arg1, atslab_0) ;
tmp79 = ats_caselptrlab_mac(anairiats_sum_11, arg1, atslab_1) ;
tmp80 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_is_prf (tmp78) ;
if (tmp80) {
arg0 = arg0 ;
arg1 = tmp79 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer ; // tail call
} else {
tmp81 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer_shallow (arg0, tmp78) ;
tmp82 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer (arg0, tmp79) ;
tmp77 = ATS_MALLOC(sizeof(anairiats_sum_11)) ;
ats_selptrset_mac(anairiats_sum_11, tmp77, atslab_0, tmp81) ;
ats_selptrset_mac(anairiats_sum_11, tmp77, atslab_1, tmp82) ;
} /* end of [if] */
break ;

/* branch: __ats_lab_39 */
__ats_lab_39_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_39_1:
tmp77 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp77) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 9610(line=429, offs=3) -- 9795(line=440, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_npf_tyer (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp83) ;
ATSlocal (ats_bool_type, tmp84) ;
ATSlocal (ats_ptr_type, tmp85) ;
ATSlocal (ats_int_type, tmp86) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_npf_tyer:
tmp84 = atspre_gt_int_int (arg1, 0) ;
if (tmp84) {
if (arg2 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 9666(line=433, offs=7) -- 9692(line=433, offs=33)") ; }
tmp85 = ats_caselptrlab_mac(anairiats_sum_11, arg2, atslab_1) ;
tmp86 = atspre_sub_int_int (arg1, 1) ;
arg0 = arg0 ;
arg1 = tmp86 ;
arg2 = tmp85 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_npf_tyer ; // tail call
} else {
tmp83 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer (arg0, arg2) ;
} /* end of [if] */
return (tmp83) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_npf_tyer] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 9916(line=448, offs=5) -- 10630(line=482, offs=4)
*/
ATSstaticdec()
ats_ptr_type
auxlst_15 (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2, ats_int_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp88) ;
ATSlocal (ats_bool_type, tmp89) ;
ATSlocal (ats_ptr_type, tmp90) ;
ATSlocal (ats_int_type, tmp91) ;
ATSlocal (ats_int_type, tmp92) ;
ATSlocal (ats_ptr_type, tmp93) ;
ATSlocal (ats_ptr_type, tmp94) ;
ATSlocal (ats_bool_type, tmp95) ;
ATSlocal (ats_int_type, tmp96) ;
ATSlocal (ats_ptr_type, tmp97) ;
ATSlocal (ats_ptr_type, tmp98) ;
ATSlocal (ats_ptr_type, tmp99) ;
ATSlocal (ats_ptr_type, tmp100) ;
ATSlocal (ats_ptr_type, tmp101) ;
ATSlocal (ats_int_type, tmp102) ;

__ats_lab_auxlst_15:
tmp89 = atspre_gt_int_int (arg1, 0) ;
if (tmp89) {
if (arg2 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 10032(line=455, offs=7) -- 10058(line=455, offs=33)") ; }
tmp90 = ats_caselptrlab_mac(anairiats_sum_11, arg2, atslab_1) ;
tmp91 = atspre_sub_int_int (arg1, 1) ;
tmp92 = atspre_add_int_int (arg3, 1) ;
arg0 = arg0 ;
arg1 = tmp91 ;
arg2 = tmp90 ;
arg3 = tmp92 ;
goto __ats_lab_auxlst_15 ; // tail call
} else {
do {
/* branch: __ats_lab_40 */
__ats_lab_40_0:
if (arg2 == (ats_sum_ptr_type)0) { goto __ats_lab_41_0 ; }
__ats_lab_40_1:
tmp93 = ats_caselptrlab_mac(anairiats_sum_11, arg2, atslab_0) ;
tmp94 = ats_caselptrlab_mac(anairiats_sum_11, arg2, atslab_1) ;
tmp95 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_is_prf (tmp93) ;
if (tmp95) {
tmp96 = atspre_add_int_int (arg3, 1) ;
arg0 = arg0 ;
arg1 = arg1 ;
arg2 = tmp94 ;
arg3 = tmp96 ;
goto __ats_lab_auxlst_15 ; // tail call
} else {
tmp97 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__label_make_int (arg3) ;
tmp98 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer_shallow (arg0, tmp93) ;
tmp100 = (ats_sum_ptr_type)0 ;
tmp99 = ATS_MALLOC(sizeof(anairiats_sum_12)) ;
ats_selptrset_mac(anairiats_sum_12, tmp99, atslab_0, tmp97) ;
ats_selptrset_mac(anairiats_sum_12, tmp99, atslab_1, tmp100) ;
ats_selptrset_mac(anairiats_sum_12, tmp99, atslab_2, tmp98) ;
tmp102 = atspre_add_int_int (arg3, 1) ;
tmp101 = auxlst_15 (arg0, arg1, tmp94, tmp102) ;
tmp88 = ATS_MALLOC(sizeof(anairiats_sum_11)) ;
ats_selptrset_mac(anairiats_sum_11, tmp88, atslab_0, tmp99) ;
ats_selptrset_mac(anairiats_sum_11, tmp88, atslab_1, tmp101) ;
} /* end of [if] */
break ;

/* branch: __ats_lab_41 */
__ats_lab_41_0:
// if (arg2 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_41_1:
tmp88 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
} /* end of [if] */
return (tmp88) ;
} /* end of [auxlst_15] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 9885(line=446, offs=3) -- 10689(line=486, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_npf_tyer_labize (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp87) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_npf_tyer_labize:
tmp87 = auxlst_15 (arg0, arg1, arg2, 0) ;
return (tmp87) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_npf_tyer_labize] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 10778(line=492, offs=3) -- 11261(line=513, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__labs2explst_tyer (ats_ptr_type arg0, ats_int_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp103) ;
ATSlocal (ats_ptr_type, tmp104) ;
ATSlocal (ats_ptr_type, tmp105) ;
ATSlocal (ats_ptr_type, tmp106) ;
ATSlocal (ats_ptr_type, tmp107) ;
ATSlocal (ats_ptr_type, tmp108) ;
ATSlocal (ats_bool_type, tmp109) ;
ATSlocal (ats_ptr_type, tmp110) ;
ATSlocal (ats_ptr_type, tmp111) ;
ATSlocal (ats_ptr_type, tmp112) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__labs2explst_tyer:
do {
/* branch: __ats_lab_42 */
__ats_lab_42_0:
if (arg2 == (ats_sum_ptr_type)0) { goto __ats_lab_43_0 ; }
__ats_lab_42_1:
tmp104 = ats_caselptrlab_mac(anairiats_sum_11, arg2, atslab_0) ;
tmp105 = ats_caselptrlab_mac(anairiats_sum_11, arg2, atslab_1) ;

tmp106 = ats_caselptrlab_mac(anairiats_sum_12, tmp104, atslab_0) ;
tmp107 = ats_caselptrlab_mac(anairiats_sum_12, tmp104, atslab_1) ;
tmp108 = ats_caselptrlab_mac(anairiats_sum_12, tmp104, atslab_2) ;
tmp109 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2exp_is_prf (tmp108) ;
if (tmp109) {
arg0 = arg0 ;
arg1 = arg1 ;
arg2 = tmp105 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__labs2explst_tyer ; // tail call
} else {
tmp110 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer (arg0, arg1, tmp108) ;
tmp111 = ATS_MALLOC(sizeof(anairiats_sum_12)) ;
ats_selptrset_mac(anairiats_sum_12, tmp111, atslab_0, tmp106) ;
ats_selptrset_mac(anairiats_sum_12, tmp111, atslab_1, tmp107) ;
ats_selptrset_mac(anairiats_sum_12, tmp111, atslab_2, tmp110) ;
tmp112 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__labs2explst_tyer (arg0, arg1, tmp105) ;
tmp103 = ATS_MALLOC(sizeof(anairiats_sum_11)) ;
ats_selptrset_mac(anairiats_sum_11, tmp103, atslab_0, tmp111) ;
ats_selptrset_mac(anairiats_sum_11, tmp103, atslab_1, tmp112) ;
} /* end of [if] */
break ;

/* branch: __ats_lab_43 */
__ats_lab_43_0:
// if (arg2 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_43_1:
tmp103 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp103) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__labs2explst_tyer] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 11346(line=519, offs=3) -- 11560(line=530, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__labs2explst_npf_tyer (ats_ptr_type arg0, ats_int_type arg1, ats_int_type arg2, ats_ptr_type arg3) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp113) ;
ATSlocal (ats_bool_type, tmp114) ;
ATSlocal (ats_ptr_type, tmp115) ;
ATSlocal (ats_int_type, tmp116) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__labs2explst_npf_tyer:
tmp114 = atspre_gt_int_int (arg2, 0) ;
if (tmp114) {
if (arg3 == (ats_sum_ptr_type)0) { ats_caseof_failure_handle ("/home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 11409(line=523, offs=7) -- 11437(line=523, offs=35)") ; }
tmp115 = ats_caselptrlab_mac(anairiats_sum_11, arg3, atslab_1) ;
tmp116 = atspre_sub_int_int (arg2, 1) ;
arg0 = arg0 ;
arg1 = arg1 ;
arg2 = tmp116 ;
arg3 = tmp115 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__labs2explst_npf_tyer ; // tail call
} else {
tmp113 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__labs2explst_tyer (arg0, arg1, arg3) ;
} /* end of [if] */
return (tmp113) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__labs2explst_npf_tyer] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 11649(line=536, offs=3) -- 12152(line=558, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer_apparg (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp117) ;
ATSlocal (ats_ptr_type, tmp118) ;
ATSlocal (ats_ptr_type, tmp119) ;
ATSlocal (ats_ptr_type, tmp120) ;
ATSlocal (ats_bool_type, tmp121) ;
ATSlocal (ats_bool_type, tmp122) ;
ATSlocal (ats_ptr_type, tmp123) ;
ATSlocal (ats_ptr_type, tmp124) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer_apparg:
do {
/* branch: __ats_lab_44 */
__ats_lab_44_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_45_0 ; }
__ats_lab_44_1:
tmp118 = ats_caselptrlab_mac(anairiats_sum_11, arg1, atslab_0) ;
tmp119 = ats_caselptrlab_mac(anairiats_sum_11, arg1, atslab_1) ;
tmp120 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_2, tmp118), atslab_s2exp_srt) ;
tmp121 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_is_prgm (tmp120) ;
if (tmp121) {
tmp122 = ats_true_bool ;
} else {
tmp122 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__s2rt_is_tkind (tmp120) ;
} /* end of [if] */
if (tmp122) {
tmp123 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer_shallow (arg0, tmp118) ;
tmp124 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer_apparg (arg0, tmp119) ;
tmp117 = ATS_MALLOC(sizeof(anairiats_sum_11)) ;
ats_selptrset_mac(anairiats_sum_11, tmp117, atslab_0, tmp123) ;
ats_selptrset_mac(anairiats_sum_11, tmp117, atslab_1, tmp124) ;
} else {
arg0 = arg0 ;
arg1 = tmp119 ;
goto __ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer_apparg ; // tail call
} /* end of [if] */
break ;

/* branch: __ats_lab_45 */
__ats_lab_45_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_45_1:
tmp117 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp117) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__s2explst_tyer_apparg] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 12281(line=566, offs=5) -- 12550(line=582, offs=4)
*/
ATSstaticdec()
ats_ptr_type
aux_20 (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp127) ;
ATSlocal (ats_ptr_type, tmp128) ;
ATSlocal (ats_ptr_type, tmp129) ;
ATSlocal (ats_ptr_type, tmp130) ;
ATSlocal (ats_ptr_type, tmp131) ;

__ats_lab_aux_20:
do {
/* branch: __ats_lab_46 */
__ats_lab_46_0:
if (arg1 == (ats_sum_ptr_type)0) { goto __ats_lab_47_0 ; }
__ats_lab_46_1:
tmp128 = ats_caselptrlab_mac(anairiats_sum_11, arg1, atslab_0) ;
tmp129 = ats_caselptrlab_mac(anairiats_sum_11, arg1, atslab_1) ;
tmp130 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__s2exp_tyer_shallow (arg0, tmp128) ;
tmp131 = aux_20 (arg0, tmp129) ;
tmp127 = ATS_MALLOC(sizeof(anairiats_sum_11)) ;
ats_selptrset_mac(anairiats_sum_11, tmp127, atslab_0, tmp130) ;
ats_selptrset_mac(anairiats_sum_11, tmp127, atslab_1, tmp131) ;
break ;

/* branch: __ats_lab_47 */
__ats_lab_47_0:
// if (arg1 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_47_1:
tmp127 = (ats_sum_ptr_type)0 ;
break ;
} while (0) ;
return (tmp127) ;
} /* end of [aux_20] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 12232(line=563, offs=15) -- 12608(line=586, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarg_tyer (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp125) ;
ATSlocal (ats_ptr_type, tmp126) ;
ATSlocal (ats_ptr_type, tmp132) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarg_tyer:
tmp126 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_13, arg0), atslab_t2mpmarg_loc) ;
tmp132 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_13, arg0), atslab_t2mpmarg_arg) ;
tmp125 = aux_20 (tmp126, tmp132) ;
return (tmp125) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarg_tyer] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 52519(line=1874, offs=5) -- 52952(line=1891, offs=4)
*/
ATSstaticdec()
ats_void_type
loop_24 (ats_ptr_type arg0, ats_ptr_type arg1, ats_ref_type arg2, ats_ptr_type arg3) {
/* local vardec */
// ATSlocal_void (tmp137) ;
ATSlocal (ats_ptr_type, tmp138) ;
ATSlocal (ats_ptr_type, tmp139) ;
ATSlocal (ats_ptr_type, tmp140) ;
ATSlocal (ats_ptr_type, tmp141) ;
ATSlocal (ats_ptr_type, tmp142) ;
ATSlocal (ats_ptr_type, tmp143) ;

__ats_lab_loop_24:
do {
/* branch: __ats_lab_48 */
__ats_lab_48_0:
if (arg0 == (ats_sum_ptr_type)0) { goto __ats_lab_49_0 ; }
__ats_lab_48_1:
tmp138 = ats_caselptrlab_mac(anairiats_sum_11, arg0, atslab_0) ;
tmp139 = ats_caselptrlab_mac(anairiats_sum_11, arg0, atslab_1) ;
tmp140 = ((ats_ptr_type(*)(ats_ptr_type, ats_ptr_type))arg1) (tmp138, arg3) ;
tmp141 = ATS_MALLOC(sizeof(anairiats_sum_11)) ;
ats_selptrset_mac(anairiats_sum_11, tmp141, atslab_0, tmp140) ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp141 ;
// if (ats_ptrget_mac(ats_ptr_type, arg2) == (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
tmp142 = &ats_caselptrlab_mac(anairiats_sum_11, ats_ptrget_mac(ats_ptr_type, arg2), atslab_1) ;
arg0 = tmp139 ;
arg1 = arg1 ;
arg2 = tmp142 ;
arg3 = arg3 ;
goto __ats_lab_loop_24 ; // tail call
break ;

/* branch: __ats_lab_49 */
__ats_lab_49_0:
// if (arg0 != (ats_sum_ptr_type)0) { ats_deadcode_failure_handle () ; }
__ats_lab_49_1:
tmp143 = (ats_sum_ptr_type)0 ;
ats_ptrget_mac(ats_ptr_type, arg2) = tmp143 ;
break ;
} while (0) ;
return /* (tmp137) */ ;
} /* end of [loop_24] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 52444(line=1870, offs=3) -- 53099(line=1899, offs=4)
*/
ATSstaticdec()
ats_ptr_type
list_map_funenv_01412_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1, ats_ptr_type arg2) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp136) ;
ATSlocal (ats_ptr_type, tmp144) ;
// ATSlocal_void (tmp145) ;

__ats_lab_list_map_funenv_01412_ats_ptr_type_ats_ptr_type:
/* ats_ptr_type tmp144 ; */
/* tmp145 = */ loop_24 (arg0, arg1, (&tmp144), arg2) ;
tmp136 = tmp144 ;
return (tmp136) ;
} /* end of [list_map_funenv_01412_ats_ptr_type_ats_ptr_type] */

/*
// /home/hwxi/research/Anairiats/prelude/DATS/list.dats: 53173(line=1904, offs=3) -- 53424(line=1911, offs=2)
*/
ATSstaticdec()
ats_ptr_type
list_map_fun_01413_ats_ptr_type_ats_ptr_type (ats_ptr_type arg0, ats_ptr_type arg1) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp135) ;

__ats_lab_list_map_fun_01413_ats_ptr_type_ats_ptr_type:
tmp135 = list_map_funenv_01412_ats_ptr_type_ats_ptr_type (arg0, ats_castfn_mac(ats_ptr_type, arg1), atspre_null_ptr) ;
return (tmp135) ;
} /* end of [list_map_fun_01413_ats_ptr_type_ats_ptr_type] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 12663(line=589, offs=18) -- 12759(line=593, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarglst_tyer (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp133) ;
ATSlocal (ats_ptr_type, tmp134) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarglst_tyer:
tmp134 = list_map_fun_01413_ats_ptr_type_ats_ptr_type (arg0, &_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarg_tyer) ;
tmp133 = ats_castfn_mac(ats_ptr_type, tmp134) ;
return (tmp133) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarglst_tyer] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 12840(line=599, offs=3) -- 12985(line=605, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarg_mhnfize (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp146) ;
ATSlocal (ats_ptr_type, tmp147) ;
ATSlocal (ats_ptr_type, tmp148) ;
ATSlocal (ats_ptr_type, tmp149) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarg_mhnfize:
tmp147 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_13, arg0), atslab_t2mpmarg_loc) ;
tmp148 = ats_selbox_mac(ats_castptr_mac(anairiats_rec_13, arg0), atslab_t2mpmarg_arg) ;
tmp149 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__s2explst_mhnfize (tmp148) ;
tmp146 = _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__t2mpmarg_make (tmp147, tmp149) ;
return (tmp146) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarg_mhnfize] */

/*
// /home/hwxi/research/Postiats/git/src/pats_typerase_staexp.dats: 13048(line=609, offs=3) -- 13151(line=615, offs=4)
*/
ATSglobaldec()
ats_ptr_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarglst_mhnfize (ats_ptr_type arg0) {
/* local vardec */
ATSlocal (ats_ptr_type, tmp150) ;
ATSlocal (ats_ptr_type, tmp151) ;

__ats_lab__2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarglst_mhnfize:
tmp151 = list_map_fun_01413_ats_ptr_type_ats_ptr_type (arg0, &_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarg_mhnfize) ;
tmp150 = ats_castfn_mac(ats_ptr_type, tmp151) ;
return (tmp150) ;
} /* end of [_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__t2mpmarglst_mhnfize] */

/* static load function */

// extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__staload (void) ;
extern ats_void_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__staload (void) ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__staload () {
static int _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__staload_flag = 0 ;
if (_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__staload_flag) return ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__staload_flag = 1 ;

// _2home_2hwxi_2research_2Postiats_2git_2src_2pats_atspre_2edats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_basics_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_label_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_staexp2_util_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_histaexp_2esats__staload () ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_2esats__staload () ;

return ;
} /* staload function */

/* dynamic load function */

// dynload flag declaration
extern ats_int_type _2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__dynload_flag ;

ats_void_type
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__dynload () {
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__dynload_flag = 1 ;
_2home_2hwxi_2research_2Postiats_2git_2src_2pats_typerase_staexp_2edats__staload () ;

#ifdef _ATS_PROOFCHECK
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_2esats__list_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2SATS_2list_vt_2esats__list_vt_length_is_nonnegative_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2SATS_2array_2esats__array_v_takeout2_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2list_vt_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____copy_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____free_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
ATS_2d0_2e2_2e10_2prelude_2DATS_2array_2edats____assert_prfck () ;
#endif /* _ATS_PROOFCHECK */

/* marking static variables for GC */

/* marking external values for GC */

/* code for dynamic loading */
return ;
} /* end of [dynload function] */

/* external codes at mid */
/* external codes at bot */

/* ****** ****** */

/* end of [pats_typerase_staexp_dats.c] */
